### ISSUE TITLE
Auto-create scenario test functions

### ISSUE THREAD

**Issue by santagada** [pytest-dev/pytest-bdd#103]
pytest-bdd would be much more awesome if it would auto create scenario functions, so you wouldn't have to define empty functions just to make the test go. I think this either could be implemented as a test collector (also would make the test reporter more user friendly as it would show the feature file as the source of tests) or it could be just a invocation form of scenario function like:

scenario('feature/something.feature', auto=True)

**Comment by bubenkoff** [comment]
But there's auto generation for that
Did you try it?

**Comment by blueyed** [comment]
@bubenkoff 
Are you referring to https://github.com/pytest-dev/pytest-bdd/blob/master/README.rst#test-code-generation-helpers?

I think what @santagada is a bit more involved (if I understand it correctly): the advanced code generator would say "Scenario is not bound to any test":

    Please place the code above to the test file(s):

    @scenario('tests/generation.feature', 'Code is generated for scenarios which are not bound to any tests')
    def test_Code_is_generated_for_scenarios_which_are_not_bound_to_any_tests():
        """Code is generated for scenarios which are not bound to any tests."""

But this seems to be redundant. It would be nice if the scenario files could
be considered to be (pytest) tests automatically.

**Comment by bubenkoff** [comment]
Yes I'm about that
I wanted all of interested people to play with existing possibilities first.
I'm more than open for the change, just it should really improve things.

**Comment by blueyed** [comment]
Cool.

What are your current thoughts on providing this?
I see that [behave](https://pypi.python.org/pypi/behave) does this automatically.

I've thought that maybe pytest would require the test functions to collect any tests, but that can be certainly hooked into / provided in a different way.

**Comment by bubenkoff** [comment]
there are discussions in #89 and #92

**Comment by blueyed** [comment]
I like the idea from https://github.com/pytest-dev/pytest-bdd/issues/90#issuecomment-69065075, where you would import / create tests for a set of scenarios:

    scenarios('my.feature')

This could then also support using directories (with or without recursion), which would allow to set up all features like:

    scenarios()

And for directories:

    scenarios('frontend', recurse=True)  # recurse=True could be the default

It's probably useful to also accept an iterable here, allowing to fine tune it using some generators etc.

(please keep in mind that I am new to pytest-bdd, so am lacking any experience in this regard)

**Comment by bubenkoff** [comment]
this will only work for simple cases, but if you'll need to parametrize certain test directly on the function level, then you'll need a way to exclude certain test from that automatic 'suite'

**Comment by santagada** [comment]
The problem with the generator is that it is too manual. There should be some way to auto collect tests, just like py.test does for functions and all.

**Comment by bubenkoff** [comment]
I'll try to experiment with this (again)

**Comment by santagada** [comment]
It is starting to look good :+1:

**Comment by bubenkoff** [comment]
2.7.0. is out
please play and say what you think

**Comment by spinus** [comment]
@bubenkoff I only wanted to say cheers, good stuff :-)

**Comment by bubenkoff** [comment]
@spinus thanks, have you tried it?

**Comment by spinus** [comment]
Yes, works almost nice :-) (#139)

**Comment by evbo** [comment]
@bubenkoff as a newcomer to pytest-bdd, it's very hard to discern in your docs how to automatically generate `feature` files from `.._test.py` files, or vice-a-versa.

Could you link me to where it's documented how to generate 1 from the other?

**Comment by bubenkoff** [comment]
@evbo do you mean https://github.com/pytest-dev/pytest-bdd#test-code-generation-helpers
but it's a generation of the step definitions, not the steps. The vice versa wouldn't make any sense to me, as this is a behavior-driven development, where the feature in plain text precedes anything else.

**Comment by evbo** [comment]
@bubenkoff thank you, that's perfect and I answered a similar Discussion with references. Someone else was also looking for a way to define `.features` from test code.

Here's my take on what people like me are looking for: A way to automatically document their code (auto-convert to `.feature` or `.md` markup), while writing tests, without a product owner necessarily in the loop (for very small teams or single person businesses).

I don't think what I'm looking for exists and maybe writing my own CLI that parses the Python code of pytests wouldn't be so hard. Thank you otherwise for a great repo, maybe my use case just isn't a good fit for it.

**Comment by bubenkoff** [comment]
Not sure I personally like the idea, but you can try implementing it in PR
to demonstrate the approach and then it might get an approval from the
maintainers.
