### ISSUE TITLE
Can @when, @given, @then etc. work with instance methods?

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-bdd#108]
Can we make a class implement a scenario? Then common steps can be in a base class.

Your docs don't explicitly say one way or the other.

**Comment by bubenkoff** [comment]
This was never tested, please try :)
I suspect it needs some fixes to support class-based test suites
But please be aware about what Guido said about classes: they are not namespaces! use modules for that.

**Comment by bubenkoff** [comment]
some insight of how the steps can be organized can be taken from http://developer.paylogic.com/articles/how-we-use-pytest-and-pytest-bdd-in-paylogic.html (see the bottom of the page)

**Comment by bubenkoff** [comment]
should we leave it open?

**Comment by sureshvv** [comment]
Modules seem to suffice for our use of pytest_bdd.
