### ISSUE TITLE
Scenario Outline uses @pytest.fixture rather than @pytest.mark.parameterize

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-bdd#109]
This causes the entire scenario to be replayed rather than the parameterized steps.

Would it be possible to provide a hint to use parameterize?

**Comment by bubenkoff** [comment]
sorry, can you please explain more about the issue?
What's your feature file, and the test code?

**Comment by sureshvv** [comment]
Here is my scenario:

    Scenario Outline: Creating a user
        Given I am logged in as admin
        And I select Users and Groups in site setup
        When I add user <user>
        Then User <user> should be created

        Examples:
        | user              |
        | user1            |
        | user2            |

Now I don't want the "Given I am logged in as admin" to be executed for each user in list.
I tried to use "Background" but that didn't work either.

Hope I am being clear,

**Comment by bubenkoff** [comment]
Well, it's the nature of outline/parametrization:
single test code, multiple TESTS
the whole scenario will be executed, one time for set of parameters
Why would you not want to run ```Given I am logged in as admin```?
tests should be isolated, and making test setup (given is the setup) each time is a good thing for isolation

**Comment by bubenkoff** [comment]
if you use pytest-splinter, for example, it makes sure your browser is clean every test run, so it cleans cookies

**Comment by sureshvv** [comment]
But we also want tests to run in a reasonable amount of time.
What is the mechanism to have some steps run only once but have other steps parameterized?

**Comment by sureshvv** [comment]
browser gives you a fixture with module scope, so that works very well. I can login once and run a whole bunch of things.

**Comment by sureshvv** [comment]
I think this can be done on the python file with @pytest.mark.parameterize.

It would be nice to be able to specify something in the scenario itself to get this behavior.

**Comment by bubenkoff** [comment]
well, then you can do this:

@pytest.fixture(scope='session')
def logged_in(browser):
     browser.login()

pytest_bdd.given('I am logged in as admin', fixture='logged_in')

this way you'll get what you want

**Comment by sureshvv** [comment]
Thanks. Shall try it now.

**Comment by bubenkoff** [comment]
by default, all steps are function-scoped, but that way you can make some given step to have other scope

**Comment by bubenkoff** [comment]
probably we should make it a parameter on given step

**Comment by sureshvv** [comment]
I got:
    E       ScopeMismatchError: You tried to access the 'function' scoped fixture 'browser' with a 'session' scoped request object, involved factories
    E       test_create_user.py:10:  def logged_in(browser)
    E       ../../../local/lib/python2.7/site-packages/pytest_splinter/plugin.py:359:  def browser(request, browser_instance_getter)

**Comment by sureshvv** [comment]
I tried to save an attribute called 'already_logged_in' in browser which I check before logging in.
It is set but the cookie is gone. So it is session scoped (since it had my attribute) but the cookies got lost,

**Comment by sureshvv** [comment]
pytest-splinter says it is session scoped.

**Comment by bubenkoff** [comment]
right, pytest-splinter is not ready for such use-case...
please try to change pytest_splinter/plugin.py:browser_instance_getter
it's scope to session
and then declare

````
@pytest.fixture(scope='session')
def session_browser(browser_instance_getter):
    return browser_instance_getter(session_browser)

```

and then you'd have to use session_browser for all steps of that scenario, otherwise you'll be logged off

**Comment by bubenkoff** [comment]
if you'll succeed, i'll make a new release of pytest-splinter which will include such changes

**Comment by sureshvv** [comment]
browser_instance_getter uses fixture tmpdir from pytest which is not session scoped. Should we patch/duplicate?

**Comment by sureshvv** [comment]
ok.. I made a session_tmpdir fixture and everything works.

I still get an error on teardown:

    def make_screenshot_on_failure():
>       if splinter_make_screenshot_on_failure and request.node.splinter_failure:
E       AttributeError: 'Session' object has no attribute 'splinter_failure'

/home/suresh/pytest-splinter/pytest_splinter/plugin.py:321: AttributeError

Investigating.

**Comment by sureshvv** [comment]
ok.. will send pull request

**Comment by bubenkoff** [comment]
so try pytest-splinter==1.3.4

**Comment by bubenkoff** [comment]
pytest-bdd 2.7.1 is out, you can pass scope for given steps now

**Comment by sureshvv** [comment]
Works great. You rock!
