### ISSUE TITLE
Markers with @ Prefix Can't be used in Expressions

### ISSUE THREAD

**Issue by kevinastone** [pytest-dev/pytest-bdd#112]
If you just leave off the `@` symbol, it works as expected.  The docs (wrongly) suggest that you can use the cucumber tag with that at symbol:
https://github.com/pytest-dev/pytest-bdd/blob/master/README.rst#organizing-your-scenarios

**Comment by bubenkoff** [comment]
can you please clarify
what is not correct in the docs exactly?

```
@feature-tag-1 @feature-tag-2
Feature: Tags

    @scenario-tag-1 @scenario-tag-2
    Scenario: Tags
        Given I have a bar

    @scenario-tag-10 @scenario-tag-20
    Scenario: Tags 2
        Given I have a bar
```

this is the scenario from tests and it works

**Comment by kevinastone** [comment]
This line:
```
py.test -k "@backend and @login and @successful"
```

If you try to use a tag with an `@` symbol in a complex expression, it fails.

It works for single tags/marker, like so:
```
py.test -k "@backend"
```

But the parser errors out if you try to use anything more complex.

**Comment by bubenkoff** [comment]
now i get it, will check what's going on there - thanks!

**Comment by bubenkoff** [comment]
i think the best for now is to just use this notation:

```
py.test -k "backend and login and successful"
```
@ symbol is only for feature file syntax, later it's just stripped out

**Comment by bubenkoff** [comment]
2.10.0 is out, please check
