### ISSUE TITLE
StepDefinitionNotFoundError when function name same as step name

### ISSUE THREAD

**Issue by lrowe** [pytest-dev/pytest-bdd#120]
A step name implemented by the same named function throws a StepDefinitionNotFound error as the step definition is overwritten by the function itself once it is returned from the decorator.

Test case: https://github.com/lrowe/pytest-bdd/tree/same-function-name

My initial thought was to work around this by prefixing with '__step_' the name set on the module by ``.steps.contribute_to_module`` and looked up by ``.scenario._find_step_function``, but that ran into problems with argumented steps:
```diff
diff --git a/pytest_bdd/scenario.py b/pytest_bdd/scenario.py
index 9cf4a39..966c631 100644
--- a/pytest_bdd/scenario.py
+++ b/pytest_bdd/scenario.py
@@ -84,12 +84,12 @@ def _find_step_function(request, step, scenario, encoding):
     """
     name = step.name
     try:
-        return request.getfuncargvalue(force_encode(name, encoding))
+        return request.getfuncargvalue('__step_' + force_encode(name, encoding))
     except python.FixtureLookupError:
         try:
             name = find_argumented_step_fixture_name(name, request._fixturemanager, request)
             if name:
-                return request.getfuncargvalue(name)
+                return request.getfuncargvalue('__step_' + name)
             raise
         except python.FixtureLookupError:
             raise exceptions.StepDefinitionNotFoundError(
diff --git a/pytest_bdd/steps.py b/pytest_bdd/steps.py
index 07ef4e6..d698a51 100644
--- a/pytest_bdd/steps.py
+++ b/pytest_bdd/steps.py
@@ -237,7 +237,7 @@ def contribute_to_module(module, name, func):
 
     :return: New function copy contributed to the module
     """
-    name = force_encode(name)
+    name = '__step_' + force_encode(name)
     func = recreate_function(func, module=module)
     setattr(module, name, func)
     return func
```

**Comment by bubenkoff** [comment]
good catch!
i'll look into it

**Comment by bubenkoff** [comment]
btw: can you please given a real life example when that happens?
can't imagine a step name of one word

**Comment by lrowe** [comment]
As mentioned in #122 there is the builtin ``trace`` step. I think its mostly going to catch people with debug steps – I've used ``Then screenshot`` in the past – or who are playing with the functionality, I've written ``When foo`` in the past while acquainting myself with cucumber.

**Comment by bubenkoff** [comment]
yes but that's just a debug helper
ok i see, anyway the problem is solved in referenced PR
