### ISSUE TITLE
Scenario Outline placeholders not replaced with example values in argumented steps

### ISSUE THREAD

**Issue by lrowe** [pytest-dev/pytest-bdd#124]
With Cucumber and Behave, scenario outline steps have their placeholders substituted with the real values from the current example before the step definition is looked up.

We have a library of steps with arguments implementing commonly used parts of the Splinter API. So an outlined scenario might look like this:
```cucumber
Feature: Generics
    Scenario Outline: Visit collection and page
        When I visit "/<item_type>/"
        When I click the link with text that contains "<link_text>"

    Examples: Collections
        | item_type                     | link_text                             |
        | antibody_lot                  | ENCAB000ACQ                           |
```

Using step definitions:
```python
@when(parse('I visit "{url}"'))
def when_i_visit_url(browser, base_url, url):
    full_url = urljoin(base_url, url)
    browser.visit(full_url)

@when(parse('I click the link with text that contains "{text}"'))
def click_link_with_text_that_contains(browser, text):
    anchors = browser.find_link_by_partial_text(text)
    anchors.first.click()
```

However here , the url for ``When I visit "/<item_type>/"`` is the unsubstituted string: ``"/<item_type>/"``.

**Comment by bubenkoff** [comment]
don't mix those 2 different things: argumented step and parametrized step
for parametrized step, you need to use <> notation, exactly as you wrote in the scenario (and there's no need in quotes obviously, because nothing is parsed out of the step text
so your step definitions and scenario will be:

```cucumber
Feature: Generics
    Scenario Outline: Visit collection and page
        When I visit <url>
        When I click the link with text that contains <text>

    Examples: Collections
        | url                     | text                       |
        | antibody_lot            | ENCAB000ACQ                |
```

Using step definitions:
```python
@when('I visit <url>')
def when_i_visit_url(browser, base_url, url):
    full_url = urljoin(base_url, url)
    browser.visit(full_url)

@when('I click the link with text that contains <text>')
def click_link_with_text_that_contains(browser, text):
    anchors = browser.find_link_by_partial_text(text)
    anchors.first.click()
```

it's not a problem to reuse same step both as parametrized and argumented (if you need it for other scenarios in an argumented form):

```python
@when(parse('I visit {url}'))
@when('I visit <url>'))
def when_i_visit_url(browser, base_url, url):
    full_url = urljoin(base_url, url)
    browser.visit(full_url)
```

**Comment by lrowe** [comment]
In this case we can't simply reregister the same steps as the argument is constructed from more than just the example value, which is more clearly shown in one of the later steps.
```cucumber
When I visit "/<item_type>/"
...
Then I should see an element with the css selector ".view-item.type-<item_type>"
```

This is definitely more [specification testing](http://en.wikipedia.org/wiki/Behavior-driven_development#Story_versus_specification) than BDD, but its nice to use the same tool for the job.

I hope you don't mind me filing tickets on all of these 'differences with Cucumber'! I don't have a sense of how deep a difference this one is yet.

**Comment by bubenkoff** [comment]
keep it clear and simple, and don't try to script in the scenarios:

```cucumber
When I visit <item_url>
...
Then I should see an element with the css selector <item_css_class>
```

and in the scenario example table mention full css class instead of part of it

**Comment by lrowe** [comment]
This is a specification test rather than a BDD style test, so scripting is what its all about.

Precalculating the url and css classes means expanding the number of table columns significantly but more importantly means we can't just use the existing step definition library but have to register step definitions specifically for each test.

**Comment by bubenkoff** [comment]
try that kind of definition:

```python
from pytest_bdd import when, parses

@when(parsers.parse('Then I should see an element with the css selector "{css_prefix}<item_type>"'))
def i_see(css_prefix, item_type):
    pass
```
i don't remember if i tried to combine both ever

**Comment by bubenkoff** [comment]
was it helpful? or an issue still?

**Comment by lrowe** [comment]
If we used outlined scenarios more it would have been an issue. With only a couple of examples so I registered a special step for each, e.g.:

```python
@then('I should see an element with the css selector ".view-item.type-<item_type>"')
def should_see_element_with_css_item_type(browser, item_type):
    css = ".view-item.type-{}".format(item_type)
    browsersteps.should_see_element_with_css(browser, css)
```

**Comment by bubenkoff** [comment]
but how about the variant i proposed?

**Comment by lrowe** [comment]
I didn't try your variant as it wouldn't have reduced the number of extra step definitions required vs the simple variant.

**Comment by bubenkoff** [comment]
depends much on how you implement it
need more code context

**Comment by smoustaj** [comment]
I have the following situation:

// BDD 
Scenario Outline:
        Given I'm in hello page
        When I fill  <data>
        And I fill  <age>
        ....

Examples:
       | name | age |
       | Max   |  20  |
       | John  |  30  |


//Step Definition
@when('I fill  with <name>')
 """ Function """

@when('I fill  with <age>')
 """ Function """

I would like to avoid this repetition of the same step, just because i have 2 different variables names.

Is there cleaver anyway please ?

Thanks

**Comment by bubenkoff** [comment]
i would write the filling in just one step:

```cucumber
Scenario Outline:
Given I'm in hello page
When I fill the form 
....

Examples:
| name | age |
| Max | 20 |
| John | 30 |
```

```python
@when('I fill the form ')
def when_i_fill_the_form(name, age):
    """ Function """
```

**Comment by smoustaj** [comment]
Ok thanks

**Comment by bubenkoff** [comment]
some ideas about the form testing in bdd style: 
https://github.com/paylogic/pdt/blob/master/features/admin/
