### ISSUE TITLE
Add some documentation on what the role of the scenario function is

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-bdd#127]
What kind of stuff can be done inside the function:

    @scenario(...)
    def test_001():
        # What kind of stuff can be done here?
        pass

**Comment by bubenkoff** [comment]
Good point - i'll add that.
the function decorated with scenario is an additional test function which will be executed `after` all scenario steps. You can consider it as a normal pytest test function, eg order fixtures there, call other funnctions and make assertions.

**Comment by bubenkoff** [comment]
http://pytest-bdd.readthedocs.org/en/latest/#scenario-decorator
