### ISSUE TITLE
Would be nice to be able to separate out the Examples from the Scenario Outline

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-bdd#129]
And be able to combine them independently

That way I can use the same scenario from different tests and drive them with different Example lines.

**Comment by bubenkoff** [comment]
Its possible already :)
Just the table will be in python and not in text but ad i understand your use cade is not very bdd but more a scripting.
So just use pytest.mark.parametrize for scenario test function as mentioned in docs

**Comment by bubenkoff** [comment]
Its possible already :)
Just the table will be in python and not in text but as i understand your use case is not very bdd but more a scripting.
So just use pytest.mark.parametrize for scenario test function as mentioned in docs

**Comment by bubenkoff** [comment]
http://pytest-bdd.readthedocs.org/en/latest/#combine-scenario-outline-and-pytest-parametrization
