### ISSUE TITLE
For Backgrounds with multiple scenarios

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-bdd#131]
It would be nice to have a single Examples section that can apply to all scenarios inside the background.
Now I have to repeat the Examples for each scenario inside.

**Comment by bubenkoff** [comment]
so you mean something like:

```gherkin

Feature: Eating

    Examples:
        | start | eat | left |
        |  12   |  5  |  7   |
        |  20   |  5  |  15  |

    Scenario Outline: Eating cucumbers
        Given there are <start> cucumbers
        When I eat <eat> cucumbers
        Then I should have <left> cucumbers

    Scenario Outline: Eating apples
        Given there are <start> apples
        When I eat <eat> apples
        Then I should have <left> apples

```

**Comment by sureshvv** [comment]
yep.. u got it does this work already?

**Comment by sureshvv** [comment]
More realistic:

  Feature: State change of content

   Background:
      Given Editor is logged in
      Given Member is logged in
      Given Reviewer is logged in

   Scenario: Editor create private content
      When Editor Create  <content>
      Then Member should not able to see <content>

      Examples:
      | content                         |
      | /main_1/test_statechanging_page |

   Scenario: Editor publish the content
      When Editor submit <content> for publication
      And Reviewer publishes <content>
      Then Member should able to see <content>

      Examples:
      | content                         |
      | /main_1/test_statechanging_page |

   Scenario: Editor retract the published content
      When Editor retract the <content>
      Then Member should not able to see <content>
  
      Examples:
      | content                         |
      | /main_1/test_statechanging_page |

**Comment by bubenkoff** [comment]
no it's not implemented and it's not even in gherkin language :)
but it's not a problem to implement though
i can look into it

**Comment by bubenkoff** [comment]
please check out 2.13.0 released today
