### ISSUE TITLE
Background applies to all features within feature file

### ISSUE THREAD

**Issue by itspage** [pytest-dev/pytest-bdd#135]
Let's say I have the following feature file....

```
Feature: Feature One

  Background:
    Given I have A
    And I have B

  Scenario: Do something with A
    When I do something with A
    Then something about B

Feature: Feature Two

  Background:
    Given I have A

  Scenario: Something that just needs A
    When I do something else with A
    Then something else about B

  Scenario: Something that needs B again
    Given I have B
    When I do something else with B
    Then something else about A and B
```

When running this, you'll get a:  ``Fixture "b" that implements "I have B" given step has been already used.``

Arguably, these two features should be in separate files, which would fix the issue, but is that mandatory? I think this should work.

Thanks

**Comment by bubenkoff** [comment]
would be nice if you show all the code, but i'll try to reproduce myself

**Comment by bubenkoff** [comment]
ah, actually, it's not supported by cucumber as well, so i'll implement a validation error for such a case
http://stackoverflow.com/questions/30599752/multiple-feature-inside-single-feature-file
