### ISSUE TITLE
Caching features

### ISSUE THREAD

**Issue by PSamsonov91** [pytest-dev/pytest-bdd#137]
I have a problem with caching features, when I edited scenario's step with other value, for example:
`step_was`: open page "First page" 
`step_came`: open page "Second page"
and re-run scenario, in features kept `step_was`, but not modified `step_came`

```python
feature = features.get(full_name)
if not feature:
    feature = Feature(base_path, filename, encoding=encoding)
    features[full_name] = feature
```
I don't know right-way to solve this problem. If you can, fix please.

**Comment by bubenkoff** [comment]
are you changing feature file on the fly?

**Comment by PSamsonov91** [comment]
Yes, it is a part of our test framework.

**Comment by PSamsonov91** [comment]
Oh, thanks, my mistake, I found error in feature's creation code. =)
