### ISSUE TITLE
scenarios "collector" is not deterministic (fails on parallel execution)

### ISSUE THREAD

**Issue by spinus** [pytest-dev/pytest-bdd#138]
When I use parallel execution with pytest-xdist and in the same time I use `scenarios` to "collect" the tests I have this error.

It looks like scenarios doesn't preserve test order between test execution.
```
=================================================================== ERRORS ===================================================================
____________________________________________________________ ERROR collecting gw2 ____________________________________________________________
Different tests were collected between gw0 and gw2. The difference is:
--- gw0

+++ gw2

@@ -1,3 +1,3 @@

+test_website_title_is_set.py::test_open_first_video_from_main_page
+test_website_title_is_set.py::test_open_second_video_from_main_page
 test_website_title_is_set.py::test_X_is_used_as_website_title
-test_website_title_is_set.py::test_open_second_video_from_main_page
-test_website_title_is_set.py::test_open_first_video_from_main_page
____________________________________________________________ ERROR collecting gw1 ______
```

**Comment by bubenkoff** [comment]
Need more context for this
we use `scenarios` with xdist intensively with no issues like that

**Comment by spinus** [comment]
Interesting. I thought about fixtures, but I only use few with the default scope. I'll investigate more over the week and I'll provide more info.

**Comment by bubenkoff** [comment]
pls show your code

**Comment by spinus** [comment]
@bubenkoff my fixtures are complex and it's lot of code. I tried to reproduce it in isolation and I could not repeat that. So it looks like my fixtures causing problems rather then framework itself. Sorry for false alarm.
