### ISSUE TITLE
Make pytest-bdd fail if it finds an orphan scenario

### ISSUE THREAD

**Issue by learner010** [pytest-dev/pytest-bdd#141]
Is it possible to make pytest-bdd fail the test if there is a scenario which does not have corresponding test?

Could be useful when the features are specified by stakeholders. It would prompt the developer that new feature has been added and needs to be implemented.

**Comment by bubenkoff** [comment]
can't you just use `scenarios` shortcut?

**Comment by olegpidsadnyi** [comment]
Yes, it should fail if there are steps that are not implemented if you use scenarios() to include your feature files.
If you really need something on purpose you could use generation functionality. See generation._show_missing_code_main

**Comment by learner010** [comment]
yup, tried it. Works as expected. Thanx :)
