### ISSUE TITLE
give all the steps with same name

### ISSUE THREAD

**Issue by learner010** [pytest-dev/pytest-bdd#142]
How can I use same name for all the steps? I feel the function names are meaningless once they are decorated by `@given, @then, @when`. When I name all the steps to '_', I get `Fixture _ already in use` exception. How can I instruct `pytest-bdd` not to consider steps as fixture?

**Comment by spinus** [comment]
@learner010 'given' (I'm not sure only those) steps are also pytest fixtures by default so they are registered with their name so then you can use them as argument to any pytest test function (look at pytest-bdd examples). This makes impossible to use the same name twice (at least for given steps).

**Comment by olegpidsadnyi** [comment]
That's right. And I wonder what is the use-case of making all given steps having the same name.
If they are applying the side-effect only? I believe there is a case when some other when/then step would need the value returned by a given step. This is the exchange of the information via the pytest request as a context.

**Comment by learner010** [comment]
I personally feel it very confusing. It might be useful in some context. At present, I create a scope fixture and attach every new values to it and pass it around. I am new to pytest and pytest-bdd. I would love to learn about the best practice for fixture.

**Comment by olegpidsadnyi** [comment]
PyTest request is the scope. Fixtures are variables of this context. It seems you are using BDD with very deep detailization as a script. But still it is possible to give some fixtures values with the step.
What's your full .feature file? I wonder how you are using it

**Comment by olegpidsadnyi** [comment]
For example if you are implementing primitives such as method fixture:

```python

@given(parsers.parse('the method is "{method}"'))
def set_method(method):
    return method

```

You see - the step argument is also a fixture. So you will be able to use it in the further steps:

```python

@when('the function is called with the url and method')
def make_the_request(url, method):
    scope.request = make_request(url, method)

```

**Comment by learner010** [comment]
Feature: Request a URL

```cucumber
Scenario: Makes GET request to a URL
    Given a url
    And method is GET
    When the function is called with the url and method
    Then the function should return the tuple with an instance of requests.Request
```

The feature is something like this. I dont think we can extract object instance from scenario as u did with {method} above. I am still learning BDD, might be my approach is too verbose or too immature. Any suggestion is appreciated. :)

**Comment by olegpidsadnyi** [comment]
I believe you should specify the behavior of your entities. It looks you are testing some API. This API perhaps implements some resources, some entities. It could be CRUD or REST whatever, but the bit or URL probably identifies the resource.

Lets imagine your resource is a Book (in the Library API).

```gherkin

Feature: Library API Book CRUD
Scenario: Get a book
    Given there's a book  # In fact can apply some side effect and insert the book in the database
    When I get the book  # This performs a GET call with the url that includes the resource id mentioned in given
    Then property X of the RESOURCE should be Y
```

I know ppl used rest navigator instance as a fixture and the result of the request was cached there so you can always access it. You can still store your result in the dict fixture like you did with the context. The problem is that pytest request is the context and should be rather computed and returned than mutated and passed along.

**Comment by spinus** [comment]
Anyway, I think this issue can be closed becuase this probably wont be implemented anyway, right?
@learner010 I think if you want this feature, simplest thing is to write simple DSL (like python konira project did).

**Comment by learner010** [comment]
ya thanx :)
