### ISSUE TITLE
How to know the step failed during scenario execution?

### ISSUE THREAD

**Issue by spinus** [pytest-dev/pytest-bdd#143]
I'm doing pytest-bdd + selenium. I'm using hooks before_step after_step to do screenshots. To annotate them I thought I can use ``pytest_bdd_after_scenario`` hook to annotate all screenshots in a scenario.
How I know that scenario/test failed?

``f1.feature``:
```
Feature: f1

  Scenario: s1
    Given 1
    When 2
    Then 3
```
``test_f1.py``:
```
from pytest_bdd import scenarios, given, when, then

scenarios('.')

@given('1')
def _1():
    pass

@when('2')
def _2():
    pass

@then('3')
def _3():
    pass
```
``conftest.py``:
```
def pytest_bdd_after_scenario(request, feature, scenario):
    print("Anything failed?")
    print(scenario.failed)
    for step in scenario.steps:
        print(step.failed)
    print()
```
Output:
```
collected 1 items 

test_f1.py::test_s1 Anything failed?
False
False
False
False
()
PASSED
```
When I change last step to:
```
@then('3')
def _3():
    assert 1==2
```
the output is:
```
collected 1 items 

test_f1.py::test_s1 Anything failed?
False
False
False
False
()
FAILED
```

Is this a bug or I should access this information in a different way?

Probably I could use pytest reporter but haven't investigated this yet and I'm not sure I can use browser fixture there.

**Comment by olegpidsadnyi** [comment]
I guess using reporting is better.
In your hook you can access the report as request.node.__scenario_report__

You can call request.node.__scenario_report__.serialize() to get dict-like traversable structure or traverse objects directly.
Scenario report has a list of step reports which have info about the step and if it failed or not:

request.node.__scenario_report__.step_reports[0].step.name
request.node.__scenario_report__.step_reports[0].step.failed

**Comment by spinus** [comment]
@olegpidsadnyi Thank you for explanations. Looks like it's overkill, I'll try the "reporter" way. Cheers.

**Comment by Vic152** [comment]
Yeah, guys so this is a bug right? Or does it work as expected? Even if I do:
`def pytest_bdd_step_error(request, feature, scenario, step, step_func, step_func_args, exception):
    print(step.failed)`
It still is `failed: False`

**Comment by Vic152** [comment]
BTW I have come up with something like this:

```
scenario_report = request.node.__scenario_report__.serialize()

    for step in range(len(scenario_report['steps'])):
        if scenario_report['steps'][step]['failed']:
            print(scenario_report['steps'][step])
```

**Comment by elliottyates** [comment]
This is helpful. Wouldn't one expect the post-test hooks to report steps or scenarios as `fail`ed if they raised unhandled exceptions?
