### ISSUE TITLE
How to recreate feature file?

### ISSUE THREAD

**Issue by spinus** [pytest-dev/pytest-bdd#145]
Hi guys,

As I'm working on reporters I need to recreate feature description. I almost have it, except two things (until now).

1. Background
2. Outline, Examples

I have this feature description:
```
Feature: Designer can log in

  In order to achieve something
  I want something
  Because it will be cool


  Some description goes here.

  Background:
    Given background OK

  @OK
  Scenario: OK
    Given OK
    When OK
    Then OK

  @Some @Tag @OK
  Scenario Outline: Scenario Scneario
    Given OK
    When OK
    And OK
    Then OK

    Examples:#
      | v1| v2|
      | 1 | 2 |
      | 3 | 4 |
```
And what I've got when doing report is (for one scenario):
```
{'steps': [{'keyword': 'Given', 'duration': 0.00012564659118652344, 'name': 'background OK', 'failed': False, 'type': 'given', 'line_number': 11}, {'keyword': 'Given', 'duration': 0.00011897087097167969, 'name': 'OK', 'failed': False, 'type': 'given', 'line_number': 31}, {'keyword': 'When', 'duration': 5.459785461425781e-05, 'name': 'OK', 'failed': False, 'type': 'when', 'line_number': 32}, {'keyword': 'And', 'duration': 5.269050598144531e-05, 'name': 'OK', 'failed': False, 'type': 'when', 'line_number': 33}, {'keyword': 'Then', 'duration': 5.14984130859375e-05, 'name': 'OK', 'failed': False, 'type': 'then', 'line_number': 34}], 'feature': {'filename': '/home/spinus/Projekty/something/features/designer_login.feature', 'rel_filename': 'features/designer_login.feature', 'tags': [], 'name': 'Designer can log in', 'line_number': 1, 'description': 'In order to achieve something\nI want something\nBecause it will be cool\nSome description goes here.'}, 'line_number': 30, 'tags': ['OK', 'Some', 'Tag'], 'name': 'Scenario Scneario'}
```
I cannot recreate background, step is integrated into scenario steps and there is no other information to detect it's a background one.
I cannot recreate scenario outline at all.

Would you mind to add background description to this dictionary and as well as reference to original scenario outline ("scenario outline" keyword in "scenario" dictionary?) or what would be any other possible solutions/ways to recreate this stuff in reporters?

UPDATE:
Also, there is no way in report to find values which were used in scenario outline instance (those from example table)

**Comment by bubenkoff** [comment]
Look at the line number in the report - it's actually correct, so you can just draw the highlight and user will see where it is
should be enough?

**Comment by bubenkoff** [comment]
about attaching the parameters, i'll work on that

**Comment by spinus** [comment]
@bubenkoff yup, with a little overhead and lines arithmetic :) I probably can recreate background steps. I think it's maybe not very convinient but I'll give a shot.

**Comment by bubenkoff** [comment]
2.15.0 is out
