### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by garlicPasta** [pytest-dev/pytest-bdd#150]
Hello,
support for datatables would be a big help. 
See following example from the cucumber reference.
https://cucumber.io/docs/reference#data-tables

Thanks a lot.

**Comment by bubenkoff** [comment]
makes sense indeed
thanks for suggestion
i'll work on it

**Comment by PatrickMassot** [comment]
Is there any progress on this issue? It seems rather important to me, especially because of #157 which prevents bypassing data tables by repeated use of the same Given step. Or is there any way to get the equivalent of https://cucumber.io/docs/reference#data-tables using what's already in pytest_bdd?

**Comment by mbarakaja** [comment]
+1 for this feature. I coming from python **`behave`** and this feature is really useful

**Comment by bubenkoff** [comment]
I don't have time unfortunately

**Comment by mogthesprog** [comment]
any chance we can get some reviews on this or get it merged?

**Comment by mogthesprog** [comment]
for anyone interested, there's a workaround here

https://github.com/pytest-dev/pytest-bdd/pull/180#issuecomment-354878090

**Comment by gnikonorov** [comment]
Hey @olegpidsadnyi do you mind if I fix up the associated PR with this so we can merge it into master?

**Comment by VitaliyaIoffe** [comment]
Any updates?

**Comment by elchupanebrej** [comment]
Please check https://github.com/elchupanebrej/pytest-bdd-ng fork. Datatables are supported because official parser is use there
