### ISSUE TITLE
Can't set defaults for step arguments

### ISSUE THREAD

**Issue by dangitall** [pytest-dev/pytest-bdd#151]
I'd like to be able to write a step specification like this:

```
@given('there is an object')
@given(parsers.parse('there is an object named {name:s}'))
def obj(name="default"):
    return name
```

But if I do this then `name` always gets set to `"default"` even if the second step definition is used. Is there another way to achieve something like this? Or can defaults be supported for step arguments?

**Comment by dangitall** [comment]
After reading over the docs again I came up with this workaround:

```
@pytest.fixture
def name():
    return "default"

@given('there is an object')
@given(parsers.parse('there is an object named {name:s}'))
def obj(name):
    return name
```

Which isn't too bad but it still seems like it would be nice if defaults were directly supported.

**Comment by bubenkoff** [comment]
pytest-bdd is just a pytest plugin, in the end
it doesn't do what pytest cannot do either, and there's no concept of defaults for fixtures in pytest
so i like your second solution, and it's how we do it as well in paylogic test suite
