### ISSUE TITLE
addhooks/__multicall__ deprecated in pytest 2.8

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-bdd#154]
When running with pytest 2.8.2 with `-rw`:

```
WI2 .../pytest_bdd/plugin.py:17 use pluginmanager.add_hookspecs instead of deprecated addhooks() method.
WI1 .../pytest_bdd/reporting.py:147 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
```

**Comment by The-Compiler** [comment]
@olegpidsadnyi @bubenkoff It seems you are rather busy - if I open a PR to fix this and #153, will you guys be able to review/merge it and do a new release?

Alternatively I can also do the release if you prefer and give me a small list of what to do (adjust `__version__` and changelog, push git tag, anything else?) and give me PyPI access.

**Comment by olegpidsadnyi** [comment]
Please do a PR

**Comment by The-Compiler** [comment]
There you go: #163 :smile:
