### ISSUE TITLE
Wrong error with no scenarios

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-bdd#156]
This is a minor thing, but I thought I'd report it as I noticed it when doing a minimal testcase for another issue.

With this (broken) feature file:

```
Given foo
When bar
Then baz
```

we get:

```
E   pytest_bdd.exceptions.FeatureError: Given steps must be the first within the Scenario.
E   Line number: 1.
E   Line: Given foo.
E   File: /home/florian/tmp/bdd/feat.feature
```

Instead I'd expect the same as with an empty feature file:

```
E   pytest_bdd.exceptions.NoScenariosFound: ['/home/florian/tmp/bdd/feat.feature']
```

**Comment by bubenkoff** [comment]
agreed

**Comment by olegpidsadnyi** [comment]
OK, this happens in the strict mode.
And the reason of failure is not only about a step being part of scenario. It can also be a background and scenario outline.
It would require an artificial intelligence to determine the actual intention of the author. And the conclusion can only be made when entire file is parsed.
Instead I suggest splitting this condition and still raise a feature error with the message that step is not within scenario, outline or a background.
