### ISSUE TITLE
Documentation/examples of custom hooks

### ISSUE THREAD

**Issue by chfw** [pytest-dev/pytest-bdd#165]
Hi all,

I am having troubles in finding docs/examples of those custom hooks such as pytest_bdd_before_scenario .... Tried google and readthedocs and nothing is found. I wondered if I missed anything. What I need is to invoke my own hook function.

Cheers

**Comment by spinus** [comment]
What is your use case, what you are trying to do?

Those hooks are basically pytest hooks, they work the same, please check pytest documentation.

It's enough to put your implementation of your hook inside test module or ``conftest.py`` file. 
For example ``conftest.py``:
```
def pytest_bdd_before_scenario(request, feature, scenario):
    print ("this will be printed before scenario {}".format(scenario))
```

**Comment by chfw** [comment]
My use case is as simple as to perform certain routine before each scenario. I was not aware that it should be put in conftest.py and I give it a go today. Thanks for your answer.

**Comment by mattelacchiato** [comment]
I've had the same problem. I didn't know anything about `conftest.py`. The link in the documentation is also not valid anymore (http://pytest.org/latest/plugins.html#well-specified-hooks)

**Comment by youtux** [comment]
True, we should probably update the docs with an example, and also fix the broken link.

**Comment by monicalicareti** [comment]
Hello,

Aside from the hook functions defined in the documentation of pytest-bdd, is it possible to define other custom hooks? Something like pytest_bdd_before_feature?

I've tried to do this according to pytest docs, but the hook functions I created never get executed.
