### ISSUE TITLE
pytest-bdd callbacks not called

### ISSUE THREAD

**Issue by PiotrNestor** [pytest-dev/pytest-bdd#174]
How to get the pytest-bdd callbacks
I tried the following implementation(,but the callback is NOT called):

``` python
import pytest

@pytest.mark.tryfirst
def pytest_bdd_after_scenario(request, feature, scenario):
    print("After scenario")
```

The complete example:
Execute with: _PYTHONPATH=. python outline.py_

_outline.feature_

```
Feature: Example

Scenario Outline: Outlined given, when, then
Given there are <start> cucumbers
When I eat <eat> cucumbers
Then I should have <left> cucumbers

Examples:
| start | eat | left |
|  12   |  5  |  7   |
|  12   |  6  |  6   |
```

_outline.py_

``` python
import pytest
from pytest_bdd import given, when, then, scenario
from steps import *

@scenario(
    'outline.feature',
    'Outlined given, when, then',
    example_converters=dict(start=int, eat=float, left=str)
)
def test_outlined():
    pass

if __name__ == '__main__':
    pytest.main(args=['-q', '-s', __file__])
```

_steps.py_

``` python
import pytest
from pytest_bdd import given, when, then, scenario

@pytest.mark.tryfirst
def pytest_bdd_after_scenario(request, feature, scenario):
    print("After scenario")


@given('there are <start> cucumbers')
def start_cucumbers(start):
    print("\nStart")
    assert isinstance(start, int)
    return dict(start=start)


@when('I eat <eat> cucumbers')
def eat_cucumbers(start_cucumbers, eat):
    print("Eat")
    assert isinstance(eat, float)
    start_cucumbers['eat'] = eat


@then('I should have <left> cucumbers')
def should_have_left_cucumbers(start_cucumbers, start, eat, left):
    print("Validate result")
    assert isinstance(left, str)
    assert start - eat == int(left)
    assert start_cucumbers['start'] == start
    assert start_cucumbers['eat'] == eat
```

**Comment by The-Compiler** [comment]
`pytest_bdd_after_scenario` is a pytest hook, so I'd guess you need to implement it in a `conftest.py` in order to work.

**Comment by amakhnach** [comment]
https://docs.pytest.org/en/latest/writing_plugins.html#plugin-discovery-order-at-tool-startup

**Comment by Immanuel-Codoid** [comment]
How to run multiple scenarios in a feature file with single browser instance and not restarting the browser instance separately for each scenarios using pytest-bdd?

**Comment by jsa34** [comment]
> How to run multiple scenarios in a feature file with single browser instance and not restarting the browser instance separately for each scenarios using pytest-bdd?

This looks like a different query.

Please raise as a separate issue if still an issue

**Comment by jsa34** [comment]
As @The-Compiler stated, the hook needs to be implemented in a conftest.py or using the plugins approaches described in the link by @amakhnach 

Please feel free to reopen if this is still an issue after looking at these, @PiotrNestor and I hope your issue was resolved!
