### ISSUE TITLE
pytest-bdd tests skipped if you provide --base-url option

### ISSUE THREAD

**Issue by davidemoro** [pytest-dev/pytest-bdd#178]
Hi,
I have the following structure with both traditional tests (``tests_nobdd_login.py``) and BDD-like tests:
```
├── features
│   └── auth
│       └── login.feature
├── __init__.py
├── testing.py
└── tests
    ├── conftest.py
    ├── functional
    │   ├── auth
    │   │   ├── __init__.py
    │   │   └── test_login.py
    │   ├── conftest.py
    │   ├── __init__.py
    └── test_nobdd_login.py
```

Without ``base-url`` option the BDD test runs:
```
$ py.test -k "not nobdd" my/dummy_tests
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/user/Repository/vm-tests/src/my.dummy_tests, inifile: 
plugins: bdd-2.16.1, selenium-1.2.1, variables-1.4, html-1.8.0
collected 2 items 

my/dummy_tests/tests/functional/auth/test_login.py .
```

Providing ``--base-url`` (needed by ``test_nobdd_login.py``) instead the BDD tests are skipped:
```
$ py.test --base-url http://google.com -k "not nobdd" my/dummy_tests
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/user/Repository/vm-tests/src/my.dummy_tests, inifile: 
plugins: bdd-2.16.1, selenium-1.2.1, variables-1.4, html-1.8.0
collected 2 items 

my/dummy_tests/tests/functional/auth/test_login.py s
```

**Note well**: the my/dummy_tests/tests/functional/auth/test_login.py is a simple dummy test with no dependencies fixtures and with a simple ``assert 1``.

**Comment by The-Compiler** [comment]
Hmm, that seems odd - any chance you could create a minimal repo where I can reproduce the problem?

Also, what gets shown as skip reason if you invoke pytest with `-rs`?

**Comment by davidemoro** [comment]
Hi @The-Compiler, thank you for the `-rs` hint!
I was searching for how to debug skipped tests and it solved my problems: basically the test was skipped because it was considered as destructive. So adding a ``@pytest.mark.nondestructive`` saved my day
