### ISSUE TITLE
Error when using pytest-bdd and pytest-django

### ISSUE THREAD

**Issue by gilmrjc** [pytest-dev/pytest-bdd#187]
I can't use pytest-bdd and pytest-django. For some reason the app crashes when handling the database in a BDD test.

I have a repo with a sample app that shows this behavior https://github.com/gilmrjc/testing 
If you run py.test -s you can see that pytest-django alone works well in the test with a live_server fixture, and if I don't try to use the database in the test it also works fine, but when I try to get objects from the database inside a BDD it fails. I can't use the BDD tests inside a LiveServerTestCase class, so I need to use the live_server fixture.

Why is the app crashing?

**Comment by paultiplady** [comment]
Looks like using the `transactional_db` fixture works:

```
@scenario('authentication.feature', 'Login')
def test_login(transactional_db):
    pass
```

Fixed this issue for me.
