### ISSUE TITLE
Undocumented check for Background section

### ISSUE THREAD

**Issue by skraynev** [pytest-dev/pytest-bdd#210]
There is a patch about improving handling definition steps outside of sections: https://github.com/pytest-dev/pytest-bdd/commit/cc87b5b0ddfb4cff81b53ab323bc237e9452dcfe

Check in this patch leads to error for situation, when I try to create Background section in the following way:
Background:
     When ..........
     And ......
So using "And" Step is prohibited after "When" in "Background". (It works when I use "Given" instead of "When" in this section).

I can not find any explanation in documentation why it was changed. Could you please add some note about it in documentation?

**Comment by bubenkoff** [comment]
Background is always about Given, never about When nor Then - shouldn't be obvious?

**Comment by bubenkoff** [comment]
https://github.com/cucumber/cucumber/wiki/Background

**Comment by skraynev** [comment]
@bubenkoff Thank you for the confirmation, but IMO it's still not clear and it's not documented explicitly.
I don't see any phrase like: "Steps like "Then", "When" should not be used in the "Background" section".
Moreover It possible to use single "When" step without "And".

You pointed on the page with suggestions about correct using "Background" section. The same explanations are available for Steps here: https://github.com/cucumber/cucumber/wiki/Given-When-Then . After reading these docs I agree, that "When" and "Then" are not compatible with target of "Background", but again: it's not clear for newcomers. And the first idea about added message in exception, that I have a wrong syntax: "Step definition outside of a Scenario or a Background", why "outside"? 
I suppose, that clear way is to say: "%mode is wrongly used for "Background" section". Probably you tried to handle all potential issues, but it's really confusing, when user get such error for Logical [because it's not  clearly documented] (not syntax) error.

p.s. probably I may ignore this issue, but the reason, why I raised it, is: I tried to execute tests written by another guy a year ago (before mentioned patch ) and ... he used "When" with a lot of "And" in most places for "Background" section. So I suppose, that the ideas, which you call "obvious" were not such "obvious" for him :)

**Comment by bubenkoff** [comment]
ah sorry i missed the point that single when is still allowed - that is an obvious bug
agree to also include the notice about what is allowed in the background

**Comment by bubenkoff** [comment]
would you mind working on PR for this?

**Comment by skraynev** [comment]
If you mean to contribute it to project - yes, I can do it later on this week and then I will ask you to review.

**Comment by bubenkoff** [comment]
yes, thanks!
