### ISSUE TITLE
when step couldn't be found as a fixture

### ISSUE THREAD

**Issue by junpengl** [pytest-dev/pytest-bdd#212]
I not sure if this is a bug or it is supposed to be like this. I found that the "When" step can't be used as a fixture. 

Feature file:
```
Scenario: Arguments for given, when, thens
    Given there are 5 cucumbers

    When I eat 3 cucumbers
    And I eat 2 cucumbers

    Then I should have 0 cucumbers
```

Test file:
```
from pytest_bdd import scenario, given, when, then, parsers


@scenario('arguments.feature', 'Arguments for given, when, thens')
def test_arguments():
    pass


@given(parsers.parse('there are {start:d} cucumbers'))
def start_cucumbers(start):
    return dict(start=start, eat=0)


@when(parsers.parse('I eat {eat:d} cucumbers'))
def eat_cucumbers(start_cucumbers, eat):
    start_cucumbers['eat'] += eat
    return 5


@then(parsers.parse('I should have {left:d} cucumbers'))
def should_have_left_cucumbers(start_cucumbers, eat_cucumbers, start, left):
    assert start_cucumbers['start'] == start
    assert start - start_cucumbers['eat'] == left
```
When I ran code above, I receive 

>   @scenario('arguments.feature', 'Arguments for given, when, thens')
  def test_arguments():
E       fixture 'eat_cucumbers' not found

If I changed the when step to a given step then it is fine. Is "when" step not supposed to be used as a fixture?

**Comment by bubenkoff** [comment]
why would you want when step as a fixture?
it's still there of course, just not under the name of the function, but under the name of the actual step
but you should not try to use steps as fixtures, instead refactor the code the way that for the common operations there are just plain python functions

**Comment by junpengl** [comment]
@bubenkoff I was trying to do that because I want to pass a result of "When" step to the next step. But I understand your point, now I just use another fixture to store the piece of data I need to pass the information. Thanks

**Comment by bubenkoff** [comment]
@junpengl when steps should not return any 'results' normally, as they are actions

**Comment by sweepy84** [comment]
@junpengl / @bubenkoff  I don't understand - how else would you test the result of a When step in a Then step if it doesn't return anything?
Also if I put all the When actions in a fixture, then what is the point of the When step at all since I would just refer to the fixture in the Then step?

**Comment by arnauorriols** [comment]
Consider the following scenario:
```
Given a resource A
And a resource A-snapshots
When I create a new item in resource A
Then I can find the new item by id in resource A
And I can find the new item by id in resouce A-snapshots
```

Assume we are talking about an API, and the id is returned by the API when you create the item. How do you propose to make this id available in the `then` steps?

**Comment by arnauorriols** [comment]
FWIW, let me share a workaround: just wrapping the when function with `@pytest.fixture` does the trick:
```
@pytext.fixture
@when(parsers.parse('I eat {eat:d} cucumbers'))
def eat_cucumbers(start_cucumbers, eat):
    start_cucumbers['eat'] += eat
    return 5
```

**Comment by DaveTaddei-CR** [comment]
I would be grateful if someone could confirm this as well but when I use the workaround of decorating a When step as a fixture we have found that the step is executed twice. It is executed once as part of the scenario steps but then is executed a second time by the subsequent Then step.

**Comment by arnauorriols** [comment]
Yes, found out this myself. Is not a good alternative. i'm going to edit the original comment.

**Comment by jdlourenco** [comment]
@arnauorriols can you confirm if the workaround you provided in https://github.com/pytest-dev/pytest-bdd/issues/212#issuecomment-520892502 still has the issue @DaveTaddei-CR mentioned?

**Comment by 27149chen** [comment]
any update on this discussion?
@bubenkoff  can you please explain why when steps should not return any 'results'? I think @arnauorriols give us a good example. In his case, how do the "Then" step find the new item id?

**Comment by bubenkoff** [comment]
@27149chen IMO when is an action thus doesn't need to return anything
but maybe @olegpidsadnyi has some other opinion.

**Comment by gregnwosu** [comment]
found a work around    

```
@pytest.fixture
def result_holder() -> Dict[str, str]:
    return dict()


@when(parsers.parse('I eat {eat:d} cucumbers'))
def eat_cucumbers(start_cucumbers, eat, result_holder):
    start_cucumbers['eat'] += eat
    result_holder['RESULT'] = 5

@then(
parsers.parse(
        "I should see the following cargoes in cargo_ver:\n{table_with_header}"
    ))
def compare_result(result_holder):
      assert result_holder['RESULT'] == 5
```

not ideal but it works,
