### ISSUE TITLE
relax strict gherkin not set prior to feature discovery

### ISSUE THREAD

**Issue by micheletest** [pytest-dev/pytest-bdd#217]
I am trying to use the relax strict gherkin fixture. This fixture is not being set and therefore my test is erroring with ```pytest_bdd.exceptions.FeatureError: When steps must be the first or follow Given steps.```

I have tried placing the pytestbdd_strict_gherkin fixture in my tests/conftest.py to relax it for every test and in my tests/specific_feature/conftest.py to relax it for a feature. I've also tried to put it in the test file to relax it just for that test. None of the methods I've tried have worked.

```
env/lib/python3.4/site-packages/pytest_bdd/scenario.py:303: in scenario
    feature = Feature.get_feature(base_path, feature_name, encoding=encoding, strict_gherkin=strict_gherkin)
env/lib/python3.4/site-packages/pytest_bdd/feature.py:409: in get_feature
    feature = Feature(base_path, filename, encoding=encoding, strict_gherkin=strict_gherkin)
env/lib/python3.4/site-packages/pytest_bdd/feature.py:318: in __init__
    "When steps must be the first or follow Given steps", line_number, clean_line, filename)
E   pytest_bdd.exceptions.FeatureError: When steps must be the first or follow Given steps.
E   Line number: 40.
```

Is this a usage error on my part? Or does this not work?

Thanks.

**Comment by bubenkoff** [comment]
please show a bit more about your test structure
also please make sure that the folder with conftest module has __init__.py in it

**Comment by micheletest** [comment]
You are exactly right with the init.py, I've implemented my test folder structure without it.  I'm using this with selenium so I have something like this:

```
selenium
  /pages
   initi.py
   homepage.py
  /tests
    conftest.py
    /homepage
      conftest.py
      test_homepage.py
    /another_page
      conftest.py
      test_another_page.py
```

If I do include and init.py in each of my test folders this feature does work. Thanks.

**Comment by bubenkoff** [comment]
including __init__.py is required for proper fixture lookup
