### ISSUE TITLE
Function reusage for different step types of the same step name

### ISSUE THREAD

**Issue by polusok** [pytest-dev/pytest-bdd#228]
Namely i need to use one step on different levels. However steps aliases are working only for given only, or for when and then. 

This code doesn't work:
```
@given("I'm an author user")
@when("I'm an author user")
@then("I'm an author user")
def author_user(auth, author):
    auth['user'] = author.user
```
However this code is working fine:
```
@when("I'm an author user")
@then("I'm an author user")
def author_user(auth, author):
    auth['user'] = author.user
```

Please suggest how to fix this.

**Comment by polusok** [comment]
any suggestions?

**Comment by bubenkoff** [comment]
The use case doesnt make any sense to me.
Please read more about gherkin and bdd

**Comment by polusok** [comment]
I read gherkin and bdd. We are making end 2 end testing. 
We have a lot of systems in chain. The same step may be "then" in one case and "given" for another as we try to avoid code duplication.

I'm not asking you to provide some fix. However please suggest to implement such workaround on my end or where to look at to make it. Thanks in advance

**Comment by bubenkoff** [comment]
i really can't imagine the use-case, but if you ever need it - just extract function and reuse it:

```
@given('I'm an author user')
def given_author_user():
    return extracted_func()

@when('I'm an author user')
def when_author_user():
    extracted_func()

@then('I'm an author user')
def when_author_user():
    extracted_func()
```

But my suggestion to you is to reconsider what you're trying to do. It doesn't matter if it's end 2 end or not, but specification should make sense.

**Comment by polusok** [comment]
Thanks, however we're already using it in this way. 

I'm looking a way to keep it short like this 

```
@given("I'm an author user")
@when("I'm an author user")
@then("I'm an author user")
def author_user(auth, author):
    auth['user'] = author.user
```
As in this case "given" step is not found somehow due to fixture lookup

```
return get_fixture_value(request, get_step_fixture_name(name, step.type, encoding))
```
So I wonder, is it any way to patch your library to support this short form where all 3 decorators can be used at the same time on one function?

**Comment by The-Compiler** [comment]
FWIW I agree this would be an useful thing to have - I've had to do it myself before as well, and it'd be nice to just decorate one function with multiple decorators.

**Comment by polusok** [comment]
@The-Compiler how did you implemented it ?
