### ISSUE TITLE
Lowercase "and" becomes a part of the step definition

### ISSUE THREAD

**Issue by jeteon** [pytest-dev/pytest-bdd#230]
I started writing steps with a lowercase "and" as it splits out the sections nicely for me:

```gherkin
Given that I'm writing an example
and that I like the lowercase 'and'
When I run the pytest-bdd runner
Then it should find the second given step
```

but I noticed that the runner looks for a **given** starting with a lowercase "and":
```
E               StepDefinitionNotFoundError: Step definition is not found: Given "and that I like the lowercase 'and'"
``` 

So that the step definition I expect to match it doesn't:

```python
@given("that I like the lowercase 'and'")
def lower_case_and():
    # ...
    return
```

I can't think of any scenarios where this behaviour would be desirable. Should the runner not take both lower case and capitalised "and"s as being step definers?

**Comment by olegpidsadnyi** [comment]
Is it an issue? It is even not highlighted by the syntax colorer

**Comment by olegpidsadnyi** [comment]
Why don't you use extra new line to separate the section?

**Comment by jeteon** [comment]
Yeah, I know Gherkin technically uses the upper case "And". What I was pointing out is that I don't think strict compliance gives useful behaviour and it would be nice if something useful  came of using the lower case "and".

**Comment by jsa34** [comment]
This not valid gherkin syntax, and now we are using the official parser, this would not be allowed.  This would throw an error and needs to be capitalised.

Can we close as this is non-compliance and cannot be resolved as it violated Gherkin syntax, @youtux ?
