### ISSUE TITLE
Step name doesn't contain argument value in scenario outline

### ISSUE THREAD

**Issue by andreypetrenko82** [pytest-dev/pytest-bdd#235]
When I use scenario outline, and I can see that step name doesn't contain argument value in report.
In debug mode we can see that ```step.name``` contains just a name of argument. And in ```step_func_args``` we can see a value of this argument. But generated report via ```--cucumberjson``` has just a step with argument name (not its value).
Example:
```
Then I select <user_role> role
    Examples: user roles
      | user_role  |
      | Custom     |
```
And as a result generated report should contain:
```Then I select Custom role```
But it contains just an argument name: ```Then I select <user_role> role```

**Comment by olegpidsadnyi** [comment]
@andreypetrenko82 is it related to the new pytest? could you submit the complete test?

**Comment by slawek367** [comment]
Hi,
i saw something similar for example when I start test with: py.test --gherkin-terminal-reporter functional/some_test.py

Output contain only keys from example table but not values, so if you implement example:
Examples:
| some_key |
| value1      |
| value2      |

You will se in output:
for value1: Given some <some_key> ...
for value2: Given some <some_key> ...

Instead:
Given some value1
Given some value2

It is clear now?

**Comment by vinhntb** [comment]
@olegpidsadnyi  It's same issue #202. 
My scenario:

`

Feature: This is example demo

    Scenario Outline: Outlined given, when, thens
        Given there are <start> cucumbers
        When I eat <eat> cucumbers
        Then I should have <left> cucumbers

        Examples:
        | start | eat | left |
        |  12   |  5  |  7   |
        |  5    |  4  |  1   |
`

And output:
![image](https://user-images.githubusercontent.com/7419227/37636134-b4c83bd6-2c32-11e8-8445-baaf69b64090.png)

**Comment by sliwinski-milosz** [comment]
For Cucumber format add `--cucumberjson-expanded` to your command:
```
py.test --cucumberjson=<path to json report> --cucumberjson-expanded
```

For Gherkin reporter add `--gherkin-terminal-reporter-expanded` to your command:
```
py.test -s -vvv --gherkin-terminal-reporter --gherkin-terminal-reporter-expanded
```

**Comment by jsa34** [comment]
Features requested I believe are now implemented.  Feel free to reopen if the gherkin terminal reporter is missing anything that I have overlooked.  Expanded reporter no longer exists and the normal terminal reporter should provide the output requested above
