### ISSUE TITLE
--gherkin-terminal-reporter-expanded does nothing

### ISSUE THREAD

**Issue by veliakiner** [pytest-dev/pytest-bdd#247]
Regardless of whether `-s` or `-v` are set. `--gherkin-terminal-reporter` works fine.

**Comment by feuillemorte** [comment]
feature:
```python
When I start a <client>
```
run pytest:
```bash
pytest --gherkin-terminal-reporter -vv
```
output:
```bash
When I start a <client>
```
run with expand option:
```bash
pytest --gherkin-terminal-reporter --gherkin-terminal-reporter-expanded -vv
```
output:
```bash
When I start a java
```

Seems, it's working fine. Maybe documentations doesn't explain this option fine...

**Comment by Vic152** [comment]
Can you guys update the documentation I did not know how to do it until I came here.

**Comment by jsa34** [comment]
gherkin-terminal-reporter-expanded is no longer a feature flag - it's the default
