### ISSUE TITLE
The documentation should include an explanation of how testing of a scenario works

### ISSUE THREAD

**Issue by sambarluc** [pytest-dev/pytest-bdd#254]
In its current form, it is highly unclear what `pytest-bdd` actually does: does it simply generate some python code from a feature file? Does it change how tests are run? How are the `@scenario`, `@given`,... decorators used? I am trying to use `pytest-bdd`, but I resorted to reading the code and doing reverse engineering to understand how to use it.

An example: the `@given` decorator makes a `pytest` fixture. This can only be inferred from some examples, or from experimenting/looking at the code.

**Comment by halhenke** [comment]
Agree - even just a table of contents/links for the README would be a big help - atm I am just scrolling back and forth through a huge wall of text. 

There is an admirable quantity and quality of documentation for many parts of the project but atm I'm not really sure why none of my tests are being discovered with pytest.

**Comment by Vic152** [comment]
Yeah, the same here. It comes down to reading the source code. pytest-bdd should _just work_ with pytest splinter it does not really work that way. It is unclear how to use it.

I get that this is an open source project. I would be happy to contribute to it by recording some tutorials but it is difficult to infer from documentation how this should come together.

**Comment by sambarluc** [comment]
No feedback from maintainer, and I have no time to look further into this. I'm not using `pytest-bdd` any more (also for this reason).

**Comment by sliwinski-milosz** [comment]
Could you please tell us exactly what is unclear in documentation? I'll try to help you with that. Lets also focus at one issue at a time.
