### ISSUE TITLE
Why is there no @And step? - Feature Request

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest-bdd#266]
Hey Guys,

Just wondering why is there no **And** step?
How do you work around it?

**Comment by The-Compiler** [comment]
Huh, how would an "And"-step work?

**Comment by Vic152** [comment]
I worked with cucumber in Java and it had **@And**, they also had **@But**

'''
@And("^sets jms subscribe inputs source data$")
public void setJmsSubscribeData(DataTable sourceMappingData) {...
'''
Just like any other step.
So in my step definition I could have:

@given('my setup')
@when('my condition')
@then('my evaluation')
@and('another evaluation')

How do you do it now without **@And** Do you just cram everything into:
@given('my setup')
def my_setup():
    And this
    And this

**Comment by sliwinski-milosz** [comment]
We use multiple steps of the same type. For example:
```python
@when("action 1")
def action_1():
    pass

@when("action 2")
def action_2():
    pass
```

and then in feature file you can do:
```
When action 1
And action 2
Then ...
```

**Comment by Vic152** [comment]
Okay that helps. However guys think about it. It will make the code in step definitions a bit more readable I think.

**Comment by sliwinski-milosz** [comment]
Is it more readable? With current approach you are explicit where you want to use each step.

With `@and` step approach you would be able to use that `@and` step after `given`, `when` and `then` steps. Which is more flexible but may lead to breaking BDD testing rules.

Could you please provide arguments why it would be good to have these `@and` steps?

**Comment by ThrashAbaddon** [comment]
As this is python you can use convenient hack
`and_when = when`

and then have

```py
@when("action 1")
def action_1():
    pass

@and_when("action 2")
def action_2():
    pass
```

**Comment by Vic152** [comment]
Maybe a good hack but I do not use framework to hack it. I like to use things as they were intended and if they need a feature to request it. One of many reasons not using hacks is that someone will come after me. Pytest is complex as is. I would not like to have someone have to untangle my hacks.

**Comment by Vic152** [comment]
Hey Guys,
I really need @And step :) My reports do not read right. What is the process for contributing to pytest-bdd?

**Comment by sliwinski-milosz** [comment]
Simply create a fork and then open new pull request once you have the working implementation.

I am not sure if that is the official process but this is what I would do.

**Comment by youtux** [comment]
I cannot find [any documented usage](https://www.google.com/search?q="%40and"+site%3Adocs.cucumber.io) of the @and step definition in docs.cucumber.io.
In this thread there have been posted many reasons why it's not a good step decorator, so I won't re-iterate them.
Of course, you are free to use the solution suggested in https://github.com/pytest-dev/pytest-bdd/issues/266#issuecomment-448359907, that's perfectly fine.
