### ISSUE TITLE
pytest-bdd with pytest-splinter example

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest-bdd#277]
Hey Guys,

Does anybody have example of using pytest-bdd with pytest-splinter?
I tried to use "browser" fixture from splinter but I get errors that it does not exist.

Where do you import browser? Is it enough if you have pytest-splinter pip installed?
Do I need an instance of Browser() in conftest.py?

Docs tell us to use splinter but do not say how...

**Comment by bubenkoff** [comment]
except from installing pytest-splinter package, no other preparations are really needed
