### ISSUE TITLE
Question: Why do we use step_ method in step definitions?

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest-bdd#279]
Can someone tell me why the step definition needs test_ method?
Is this the way the test are discovered?

Normally in BDD frameworks the `Given` (or Background/@before )step initiates execution.

This method does not really do anything with `pass` in it.

**def test_publish():
    pass**

```from pytest_bdd import scenario, given, when, then

@scenario('publish_article.feature', 'Publishing the article')
def test_publish():
    pass


@given("I'm an author user")
def author_user(auth, author):
    auth['user'] = author.user```

**Comment by Vic152** [comment]
Hey Guys! How do you use this method?

**Comment by sliwinski-milosz** [comment]
[pytest tests discovery](https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery)
>test_ prefixed test functions or methods outside of class


[scenario decorator](https://pytest-bdd.readthedocs.io/en/latest/#scenario-decorator)
>Function decorated with scenario decorator behaves like a normal test function, which will be executed after all scenario steps. You can consider it as a normal pytest test function, e.g. order fixtures there, call other functions and make assertions


[Some more details (scenarios shortcut)](https://pytest-bdd.readthedocs.io/en/latest/#scenarios-shortcut)
>...with the manual approach you get all the power to be able to additionally parametrize the test, give the test function a nice name, document it, etc...

Does above answer your question? :)

**Comment by Vic152** [comment]
Lovely thank you!
