### ISSUE TITLE
Customize generate output

### ISSUE THREAD

**Issue by pfctdayelise** [pytest-dev/pytest-bdd#285]
With the generated step output, what do you think about making them `raise NotImplementedError` rather than `pass`?

I find the default pass a bit dangerous, as running pytest reports everything is passing!

I did implement the `@todo` marker as mentioned in the docs, but it feels safer to have exceptions be raised in case one slips through.

I poked around the code and there is a mention of templates - perhaps this is already customizable, just not documented?? 😃

**Comment by youtux** [comment]
That makes a lot of sense, feel free to make a PR.
