### ISSUE TITLE
Pytest KeyError when running the pytest on a single file

### ISSUE THREAD

**Issue by arashiqurrahman** [pytest-dev/pytest-bdd#295]
pytest version 4.3.0
pycharm 2018 3.5
python 3.7.2

When running the tests, it gives errors. I would really appreciate if someone could help.

Thanks in advance.

Testing started at 09:43 ...
/Users/brptestdevices/PycharmProjects/test_automation_ashiq_sample/venv/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_pytest_runner.py" --path /Users/brptestdevices/brp-digital-automation-qa/test_files/skidoo/test_home.py
Launching pytest with arguments /Users/brptestdevices/brp-digital-automation-qa/test_files/skidoo/test_home.py in /Users/brptestdevices/brp-digital-automation-qa

============================= test session starts ==============================
platform darwin -- Python 3.7.2, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
rootdir: /Users/brptestdevices/brp-digital-automation-qa, inifile:
plugins: xdist-1.26.1, mock-1.10.1, forked-1.0.2, bdd-3.1.0collected 1 item

test_files/skidoo/test_home.py F
test_files/skidoo/test_home.py:13 (test_home)
self = <FixtureRequest for <Function test_home>>
argname = 'pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable'

    def _get_active_fixturedef(self, argname):
        try:
>           return self._fixture_defs[argname]
E           KeyError: 'pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable'

/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py:489: KeyError

During handling of the above exception, another exception occurred:

request = <FixtureRequest for <Function test_home>>
step = <pytest_bdd.feature.Step object at 0x10a4482b0>
scenario = <pytest_bdd.feature.Scenario object at 0x10a448240>
encoding = 'utf-8'

    def _find_step_function(request, step, scenario, encoding):
        """Match the step defined by the regular expression pattern.
    
        :param request: PyTest request object.
        :param step: Step.
        :param scenario: Scenario.
    
        :return: Function of the step.
        :rtype: function
        """
        name = step.name
        try:
>           return request.getfixturevalue(get_step_fixture_name(name, step.type, encoding))

/usr/local/lib/python3.7/site-packages/pytest_bdd/scenario.py:91: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <FixtureRequest for <Function test_home>>
argname = 'pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable'

    def getfixturevalue(self, argname):
        """ Dynamically run a named fixture function.
    
        Declaring fixtures via function argument is recommended where possible.
        But if you can only decide whether to use another fixture at test
        setup time, you may use this function to retrieve it inside a fixture
        or test function body.
        """
>       return self._get_active_fixturedef(argname).cached_result[0]

/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py:478: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <FixtureRequest for <Function test_home>>
argname = 'pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable'

    def _get_active_fixturedef(self, argname):
        try:
            return self._fixture_defs[argname]
        except KeyError:
            try:
>               fixturedef = self._getnextfixturedef(argname)

/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py:492: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <FixtureRequest for <Function test_home>>
argname = 'pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable'

    def _getnextfixturedef(self, argname):
        fixturedefs = self._arg2fixturedefs.get(argname, None)
        if fixturedefs is None:
            # we arrive here because of a dynamic call to
            # getfixturevalue(argname) usage which was naturally
            # not known at parsing/collection time
            parentid = self._pyfuncitem.parent.nodeid
            fixturedefs = self._fixturemanager.getfixturedefs(argname, parentid)
            self._arg2fixturedefs[argname] = fixturedefs
        # fixturedefs list is immutable so we maintain a decreasing index
        index = self._arg2index.get(argname, 0) - 1
        if fixturedefs is None or (-index > len(fixturedefs)):
>           raise FixtureLookupError(argname, self)
E           _pytest.fixtures.FixtureLookupError: ('pytestbdd_given_the home page is accessible\nWhen the user enters the correct url on the browser\nThen the home page is viewable', <FixtureRequest for <Function test_home>>)

/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py:385: FixtureLookupError

During handling of the above exception, another exception occurred:

request = <FixtureRequest for <Function test_home>>

        'Browse homepage',
>   )
    def test_home():

test_files/skidoo/test_home.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.7/site-packages/pytest_bdd/scenario.py:162: in _execute_scenario
    step_func = _find_step_function(request, step, scenario, encoding=encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

request = <FixtureRequest for <Function test_home>>
step = <pytest_bdd.feature.Step object at 0x10a4482b0>
scenario = <pytest_bdd.feature.Scenario object at 0x10a448240>
encoding = 'utf-8'

    def _find_step_function(request, step, scenario, encoding):
        """Match the step defined by the regular expression pattern.
    
        :param request: PyTest request object.
        :param step: Step.
        :param scenario: Scenario.
    
        :return: Function of the step.
        :rtype: function
        """
        name = step.name
        try:
            return request.getfixturevalue(get_step_fixture_name(name, step.type, encoding))
        except pytest_fixtures.FixtureLookupError:
            try:
                name = find_argumented_step_fixture_name(name, step.type, request._fixturemanager, request)
                if name:
                    return request.getfixturevalue(name)
                raise
            except pytest_fixtures.FixtureLookupError:
                raise exceptions.StepDefinitionNotFoundError(
                    u"""Step definition is not found: {step}."""
                    """ Line {step.line_number} in scenario "{scenario.name}" in the feature "{feature.filename}""".format(
                        step=step,
                        scenario=scenario,
>                       feature=scenario.feature,
                    )
                )
E               pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given "the home page is accessible
E               When the user enters the correct url on the browser
E               Then the home page is viewable". Line 5 in scenario "Browse homepage" in the feature "/Users/brptestdevices/brp-digital-automation-qa/test_files/skidoo/homepage.feature

/usr/local/lib/python3.7/site-packages/pytest_bdd/scenario.py:104: StepDefinitionNotFoundError

**Comment by arashiqurrahman** [comment]
Dear @nicoddemus 

I just tried to copy paste the test results. 

I am pasting the screen shot here as well

screen shot 1
![image](https://user-images.githubusercontent.com/11049902/54363287-0ad41300-4641-11e9-9548-83503ee31822.png)

**Comment by sliwinski-milosz** [comment]
@arashiqurrahman could you please reformat your posts? Please check [quoting-code](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code) that should help you with that (especially triple quotes).

From what I can see pytest-bdd tries to find following step:
```
the home page is accessible
When the user enters the correct url on the browser
Then the home page is viewable
```
Instead it should look for:
```
the home page is accessible
```
As you can see `pytest-bdd` can't distinguish each line.

My guess is that there is a problem with formatting in your `homepage.feature` file - but it is hard to say as the formatting that you have pasted is broken. Do you have indentation in your `homepage.feature` file?

**Comment by arashiqurrahman** [comment]
screenshot 2

![image](https://user-images.githubusercontent.com/11049902/54363403-42db5600-4641-11e9-8ca6-f036140370eb.png)

**Comment by arashiqurrahman** [comment]
Hello @sliwinski-milosz 

Here is my feature file

![image](https://user-images.githubusercontent.com/11049902/54363537-7918d580-4641-11e9-8f97-a3fc963c62da.png)

**Comment by sliwinski-milosz** [comment]
Ok, I think your indentation is wrong. The problem is `pytest-bdd` doesn't handle alignment that you have in your feature file.

Please make sure that you have only 4 spaces before your `Given`, `When` and `Then` steps in the feature file and try again.

**Comment by arashiqurrahman** [comment]
Dear @sliwinski-milosz 
Worked like a charm. Thank you so much. closing the issue. :D
