### ISSUE TITLE
Decorators like @scenario should use hooks, not function reconstruction

### ISSUE THREAD

**Issue by daihaminkey** [pytest-dev/pytest-bdd#296]
**Problem.**
Сurrent implementation of decorators seems wrong. It reconstructs function by string execution and `recreate_function()` to save fixture arguments for pytest, but pytest provides way to do it without such hacks: [hooks](https://docs.pytest.org/en/latest/writing_plugins.html).

**The right way.**
Good example of using hooks is [allure](https://github.com/allure-framework/allure-python), which [decorators](https://github.com/allure-framework/allure-python/blob/master/allure-pytest/src/helper.py) mark test function with pytest `MarkDecorator` and than do custom logic with hooks.

**Why is important?**
With current implementation there is no way to combine two or more decorators of test function in one. For example, there is repeating pattern:
```
@allure.title('name')
@scenario('f.feature', 'name')
def test_my_test(my_fixture):
``` 
and while bdd decorators implemented with reflection and function reconstruction, it is impossible to create custom decorator like `@scenatio_with_title('f.feature', 'name')`, which mark function with two pytest `MarkDecorator`s

And this is not about the repeating code, it is about pytest architecture, which is created with respect of plugins. If there is no hidden profits of using function reconstruction, pytest_bdd should not use reflection ans string execution for decorators, while it can use marks and hooks.

**Comment by youtux** [comment]
https://github.com/pytest-dev/pytest-bdd/pull/540 should fix this.

**Comment by youtux** [comment]
Actually, I removed `recreate_function` some time ago from pytest-bdd, so this should be possible already for quite some time. I'll close the ticket, but if this still a problem, I'll open it again.
