### ISSUE TITLE
ScenarioExamplesNotValidError "Set of step parameters (...) should match set of example values (...)" should be a warning, not error

### ISSUE THREAD

**Issue by pfctdayelise** [pytest-dev/pytest-bdd#298]
I wanted to write a scenario outline like so:

```
  Scenario Outline: Assemble order - delivery types
    Given An order has been placed
    And the customer has chosen <type> delivery
    When the order is assembled
    Then the courier label states the order is <type> delivery

    Examples:
    | name     | label          | type     | 
    | Express  | TESTCASE-36230 | express  |
    | Standard | TESTCASE-36231 | standard |
```

Name and label are not used in the test steps, I agree it is worthy of a warning, but I don't believe it is outright wrong for Gherkin syntax. (Based on [gherkin-lint](https://github.com/vsiakka/gherkin-lint))

I can probably add a null step that uses the parameters to make the error go away, but it's not so nice.

**Comment by The-QA-Geek** [comment]
It is valid Gherkin; Cucumber would handle this without any problem. It is worth a warning - in my experience, adding unused columns to an Examples table rarely increases the clarity of the requirement. The whole point of using Gherkin is clarity of requirements.

**Comment by jsa34** [comment]
Unused param columns are allowed and the restriction was long removed.
