### ISSUE TITLE
Add built-in fixture to store data to be passed between steps

### ISSUE THREAD

**Issue by teetimeforyou** [pytest-dev/pytest-bdd#301]
**Problem**
Then in our integration tests _given_ or _when_ step do some stuff that return data needed in the next step

> for example
> _given_ add some to database and return id
> _when_ use id for create msg to microservice and then take response
> _then_ have a lot of asserts for response from _when_

for share data between steps we need to add something like this:
```
@pytest.fixture(scope='session')
def context():
    """Context object to store data to be passed between steps"""
    return Context()
```
This work around can be added in pytest-bdd for better support or perhaps where are another way out from this problem?

**Comment by Vic152** [comment]
Did you try using pytest:

1. I do not know if this would work but you could `return` in `When` and inject when into `Then`
2. You certainly can `return` ID from `Given` step like this
````
@given('I have an article')
def article(author):
    return create_test_article(author=author)
````
https://pytest-bdd.readthedocs.io/en/latest/#example

In your case it would be 
```
@given('database id')
def database_id(request)
    response = send_request(request)
    return extract_id(response)

### here is when I am not sure if you could return ###
@when('use id for create msg to microservice and then take response')
def do_something_with_id(database_id)
    return response_from_microservice(datbase_id)
``` 
https://pytest-bdd.readthedocs.io/en/latest/#step-arguments-are-fixtures-as-well

3. cache https://docs.pytest.org/en/3.0.1/cache.html
4. tempdir https://docs.pytest.org/en/3.0.1/tmpdir.html

**Comment by jsa34** [comment]
The last answer sums up exactly my thoughts - thanks @TBBle !

I personally have a test suite that uses the "context" as a function-scoped fixture, and the benefit of defining it yourself if you do need the behave-style approach is that you can type hint it: I created a typeddict with the schema of the test data and objects being passed around the tests, and it knows what is expected when called.
