### ISSUE TITLE
Scenario descriptions cause odd results

### ISSUE THREAD

**Issue by rcasperson-jc** [pytest-dev/pytest-bdd#311]
Perhaps it is not part of pytest-bdd's "subset" of Gherkin, but adding a scenario description causes issues.

Here's a scenario that has a scenario description:

```gherkin
Scenario: Do a thing
    In this scenario we do a thing.
    In this scenario description,
    it can be useful to do some explaining

    Given a thing
    When I do something
    Then something is done
```

In the above case, `pytest-bdd` treats each line of the description as a new scenario and creates three extra test cases `test_in_this_scenario_we_do_a_thing`, `test_in_this_scenario_description`, and `test_it_can_be_useful_to_do_some_explaining` and executes them without an error.

It may be easier to just allow scenario descriptions, but at the very least, I'd expect an error saying that the first line of a scenario must be a step.

**Comment by youtux** [comment]
Hey @rcasperson-jc, thanks for the report. Would you be interested in trying to fix it and make a pull request?

**Comment by rcasperson-jc** [comment]
@youtux I'd certainly be happy to, and I may have the time to do so. If/when I start work on it, I'll make it known on this issue.

**Comment by youtux** [comment]
Cool, thanks! 👍

**Comment by rbcasperson** [comment]
I've got a PR open for this. @youtux hopefully you or someone can take a look at it soon!
