### ISSUE TITLE
pytest-bdd reporting 

### ISSUE THREAD

**Issue by humming-bird-21** [pytest-dev/pytest-bdd#314]
I am using pytest-bdd for running the bdd tests. I am trying to get the results following the run using the flag --gherkin-terminal-reporter, however not able to get any results displated on terminal. --cucumberjson works and creates the json file though. 

Plus is there any html report for pytest-bdd ?

**Comment by lutostag** [comment]
Just dropping the knowledge I have for the first part: seems like with `--gherkin-terminal-reporter` I have add `-v` or `-vv` as further options. Not sure if that is as intended.

**Comment by ricwal-richa** [comment]
There are two html reporters for pytest-bdd.

- pytest-html {https://pypi.org/project/pytest-html/}
- allure-pytest-bdd {https://pypi.org/project/allure-pytest-bdd/}
