### ISSUE TITLE
Outline on feature and scenario failed on  ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by camjan27** [pytest-dev/pytest-bdd#315]
I want to have a testcase that is parametrized on both levels: Feature and scenario as in the example in the readme. However when I implemented it and run it, it returns the following error: `ValueError: too many values to unpack `

I did some investigation: It fails on  keys, values = examples[0]["rows"].  

examples[0]["rows"] returns [['start', 'eat', 'left'], [['12', '5', '7'], ['5', '4', '1']], ['fruits'], [['oranges'], ['apples']]].

I checked example_kwargs, which returns: {'eat': '5', 'fruits': 'oranges', 'start': '12', 'left': '7'}.
But I don't know if we can use this.

Can somebody confirm it, that scenario outline on both feature and scenario level don't work. I don't know if it worked before and so yes, which version of pytest-bdd should I use then.

**Comment by sliwinski-milosz** [comment]
Maybe it is fixed with https://github.com/pytest-dev/pytest-bdd/pull/272 but it has not been merged yet. Would be good also to add additional test.

**Comment by jsa34** [comment]
This is no longer possible (examples at the feature level) now we are using the official Gherkin parser.
