### ISSUE TITLE
pytest-bdd==3.2.0 breaks pytest-play (or any other non python pytest items)

### ISSUE THREAD

**Issue by davidemoro** [pytest-dev/pytest-bdd#317]
Preconditions:
* python environment with the following versions
* pytest-bdd==3.2.0 and pytest-play installed in same python environment (no relevant pytest-play version, tested with 2.3.1 version for sake of completeness)

How to reproduce:
* run pytest on a project with a pytest-play scenario

Expected result:
* test run without errors

Actual result:
* see error log
```
...
INTERNALERROR>   File "/usr/local/lib/python3.7/site-packages/pytest_bdd/plugin.py", line 104, in item_key
INTERNALERROR>     pytest_bdd_counter = getattr(item.function, '__pytest_bdd_counter__', 0)
INTERNALERROR> AttributeError: 'YAMLItem' object has no attribute 'function'
```

You can find all details and versions pinned here:
* https://github.com/davidemoro/pytest-play-docker/pull/264

Is it possible to be compatible with non-python pytest items?

All fine with previous pytest-bdd version instead (3.1.1 is ok).

**Comment by youtux** [comment]
Hi Davide, thanks for reporting this issue! I made a fix in #318, can you try that branch?

**Comment by davidemoro** [comment]
Hi @youtux, it works fine using the ``fix-bug-with-non-function-items`` branch. Thanks!

**Comment by youtux** [comment]
I just pushed version 3.2.1 to PyPI.
