### ISSUE TITLE
Request: Support docstrings argument according to gherkin syntax

### ISSUE THREAD

**Issue by jamesharris-garmin** [pytest-dev/pytest-bdd#323]
I know the current recommended method for handling multi-line steps is to just capture everything after the first line with a \n argument. but Gherkin has its own syntax for passing a big block of text to a step:

https://cucumber.io/docs/gherkin/reference/#doc-strings

Would it be better for us to support docstrings using this approach using similar approach? This would make writing features more compatible with other tools.

**Comment by youtux** [comment]
There is some progress made in this direction with the [new parser](https://github.com/pytest-dev/pytest-bdd/tree/rewrite-parser)

**Comment by jsa34** [comment]
resolved by #717 
@youtux
