### ISSUE TITLE
@then test is called twice if "test_" is in the step definition name

### ISSUE THREAD

**Issue by nickdelgrosso** [pytest-dev/pytest-bdd#331]
Because of pytest's default behavior of looking for "test_" in the test function name, pytest runs all test functions that it can find.  This is particularly problematic, I found, if you use the name "test_" in your @then function; it causes that function to run twice, first from pytest (without running the @given and @when function first), then again from pytest-bdd.  Since the runner output is essentially the same in each case, it makes it difficult to debug why a test isn't working.

Would it be possible to provide a warning message against naming things with "test_" if pytest-bdd detects this situation?

**Comment by youtux** [comment]
We could make it a warning, but keep in mind that pytest allows changing the way tests are discovered.
So one can potentially configure pytest to use the "mytest_" prefix instead, and we would mistakenly raise a warning.

**Comment by youtux** [comment]
Closing as this can be easily solved on the user side by naming avoiding the `test_` prefix.
