### ISSUE TITLE
Background steps stopped working after adding another Given - StepDefinitionNotFoundError

### ISSUE THREAD

**Issue by PeterAugustinak** [pytest-dev/pytest-bdd#336]
1. put common steps out of feature step_def file for re-usability purposes
2. run tests

Result: step definitions are not found. IDE (like Pycharm) has no problem to localize these steps.
pytest-bdd can see common steps only in conftest.py. In case to place them to any other file with completely correct definitions (like common_steps.py), it is not working.

**Comment by PeterAugustinak** [comment]
UPDATE: Seems like problem is actually when common steps are not in conftest.py, but instead in any file with different name, like common_steps.py. This is also an issue anyway.

**Comment by nik-wendt** [comment]
If I understand you correctly, I think what you want is the pytest.register_assert_rewrite() function documented here: https://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting

essentially in your test directory's __init__.py you can call this function to add locations of additional steps

```
#__init__.py
import pytest

pytest.register_assert_rewrite("directory_foo/stepfile_bar", "directory_foo/stepfile_baz" )
```

This allowed me to cross reference step functions from outside the current test_.py module

**Comment by youtux** [comment]
you should import those steps in your conftest.py:

```python
# conftest.py
from tests.common_steps import *

```

**Comment by xiaorong22** [comment]
> you should import those steps in your conftest.py:
> 
> ```python
> # conftest.py
> from tests.common_steps import *
> ```

thanks a lot, very useful for me

**Comment by jsa34** [comment]
Answer given by @youtux appears to resolve and documentation suggests using conftest.py for shared steps.
