### ISSUE TITLE
Testing functions without global state 

### ISSUE THREAD

**Issue by OverkillGuy** [pytest-dev/pytest-bdd#338]
It seems very hard to write tests for pure functions without global state.

I am trying to write a toy project of roman numeral conversion with BDD (amusingly named `pyroman`), however it seems difficult to write it in BDD. Consider the following feature:

```gherkin
Feature: Pyroman command line
  As a user
  I need to convert roman numerals from the command line
  So that I can be cool and retro

Scenario: Convert roman to decimal
  Given pyroman is installed
  When I run pyroman with "MMXXIX"
  Then pyroman returns "2029"
```
Setting aside the parsers for string, which I'm not using yet, tests would look like the following:

```py
# coding=utf-8
"""Pyroman command line feature tests."""

from pytest_bdd import (
    given,
    scenario,
    then,
    when,
)

from pyroman.cli import _main as pyroman

@scenario('features/command_line.feature', 'Convert decimal to roman')
def test_convert_decimal_to_roman():
    """Convert decimal to roman."""



@given('pyroman is installed')
def pyroman_is_installed():
    """pyroman is installed."""
    pass  # no action if we can import it successfully here


@when('I run pyroman with "MMXXIX"')
def i_run_pyroman_with_mmxxix():
    """I run pyroman with "MMXXIX"."""
    converted = pyroman("MMXXIX")

@then('pyroman returns "2029"')
def pyroman_returns_2029():
    """pyroman returns "2029"."""
    assert converted == 2029, "Pyroman should return correct translation"
    # NameError: name 'converted' is not defined
```
Is there something I'm missing? It feels wrong to have to use global state var in a (dummy) given , or ditch the joys of Gherkin/Pytest-bdd and revert to plain pytest for that kind of pure function (side-effect free) testing.

**Comment by Mark90** [comment]
Not sure if this is what you meant with "dummy given", but what I do is put this in conftest
```
@given("state")
def state():
  return dict()
```
And include that fixture in the 'when' and 'then' to carry over the result. Not the most elegant, but at least it's not global state (right?). Don't think there's another way other than putting both input and output in the 'then'.

**Comment by OverkillGuy** [comment]
That's fair, I ended up doing just that. 
Thanks for the reply, closing.
