### ISSUE TITLE
How to call any function after execution is completed

### ISSUE THREAD

**Issue by Enigmaderockz** [pytest-dev/pytest-bdd#360]
I have multiple feature files and I am running below command to run the execution.

pytest-bdd -sv --html = report.html test1.py test2.py

Once execution is done, report will be generated.

Now I have a function to send mail with attached report but there seems to be no option where I can call this function after execution is done in pytest bdd

any help or suggestions?

**Comment by v-buriak** [comment]
FYI: 
- could be useful to add additional option "--self-contained-html".
- [pytest hookspec](https://docs.pytest.org/en/2.8.7/_modules/_pytest/hookspec.html)
