### ISSUE TITLE
why I am getting below error?

### ISSUE THREAD

**Issue by vbpatel73** [pytest-dev/pytest-bdd#368]
Can anyone pls explain why I am getting this error?

@when(parsers.parse('the user searches for "{phrase}"'))
  def search_phrase(browser, phrase):
E       fixture 'phrase' not found
>       available fixtures: browser, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, ddg_home, doctest_namespace, json_metadata, metadata, monkeypatch, pytestbdd_given_the DuckDuckGo home page is displayed, pytestbdd_given_trace, pytestbdd_then_results are shown for "{phrase}", pytestbdd_then_trace, pytestbdd_when_the user searches for "{phrase}", pytestbdd_when_trace, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, trace, worker_id
>       use 'pytest --fixtures [testpath]' for help on them.

in my feature file it is like:

When the user searches for "panda"

**Comment by olegpidsadnyi** [comment]
Most likely for pytest reasons. Step decorators don't register steps in any global registry. They behave as pytest fixtures. Therefore they have to be imported in your confstest.py
