### ISSUE TITLE
Poorly signalled breaking change in 4.0.0

### ISSUE THREAD

**Issue by nigelmegitt** [pytest-dev/pytest-bdd#385]
Release 4.0.0 broke my build. I went to the docs. Buried right at the end: "Migration of your tests from versions 3.x.x" 

It would be _really_ helpful if you would signal that this version brings breaking changes at the _top_ of the docs, and maybe explain something about _why_ this change has been made. There appears to be no obvious user benefit to making Given steps no longer fixtures, but I'm prepared to learn! Maybe I missed something. Right now it just looks like extra work. Until I can resolve this, I'm staying with <4.0.0. It may well take quite a lot of effort to fix just to get 4.0.0 compatibility.

Thank you for the great work on pytest-bdd!

**Comment by The-Compiler** [comment]
Not sure if this should really be more prominent in the README given that it doesn't concern new users and already is [at the top of the changelog](https://pytest-bdd.readthedocs.io/en/latest/#changelog) (though missing a 4.0.0 header apparently).

As for the motivation for the change, I'm not entirely sure - I'd have hoped that change (#376) would fix #157, but I'm not sure if it actually does.

**Comment by youtux** [comment]
There was a problem with the automation of the documentation builds. That is why version 4.0.0 was not showing up.
It should be fixed now.

@nigelmegitt you should probably expect any library to break backwards compatibility with new major versions.
pytest-bdd is no different. We follow [semantic versioning](https://semver.org/).
Consider pinning your dependencies to a release your code is compatible with, for example using the [~=](https://www.python.org/dev/peps/pep-0440/#compatible-release) operator. In this way the package manager would not have upgraded automatically pytest-bdd to version 4.0.0 in your project.

**Comment by nigelmegitt** [comment]
@youtux sure, major versions might contain breaking changes, but usually with some suggestion of the motivation behind them, or benefit arising. Earlier, @The-Compiler pointed to the changelog, but that changelog is practically unreachable from one obvious major route to the documentation, [pypi.org](https://pypi.org/project/pytest-bdd/4.0.0/), where the Release history does not include a link to the changelog, and the [homepage link](https://github.com/pytest-dev/pytest-bdd) only shows this GitHub repo's README, which _does_ link to the documentation, but _only_ very subtly from the "docs passing" label. I'm not a detective - it would really help to make this easier to find.

On the subject of motivation for the change,  I've read #157 and I'm still not clear why making Givens _not_ a fixture is considered a solution to that issue; it actually seems perverse from a semantic perspective: if a Given doesn't define a fixture, what does?! I will comment on the issue directly.

**Comment by The-Compiler** [comment]
FWIW I found the changelog looking at the `CHANGES.rst` file here on GitHub, which I consider one of the standard places for a changelog :wink: If you use a tool like pyup.io to automate dependency upgrades, it'll [also pick it up from there](https://pyup.io/changelogs/pytest-bdd/).

I now also added a link to the docs to the GitHub repo as website:

![image](https://user-images.githubusercontent.com/625793/92522828-9ff89d80-f21f-11ea-9a33-d90ae727368f.png)

We can't control what PyPI shows on its release history page.

**Comment by nigelmegitt** [comment]
Thanks @The-Compiler I think that link to the docs from the GitHub repo main page is probably the best you can reasonably do. I guess you could link to the changes from the main docs page that PyPI shows, but that maybe is a "nice to have".
