### ISSUE TITLE
Scenario in scenario

### ISSUE THREAD

**Issue by nubbelle** [pytest-dev/pytest-bdd#393]
Hello! i think, it's can be helpful with scenario steps.

I have 2 scenarios:

> Scenario: 1
>     When ...
>     Then ...
> 
> Scenario: 2
>     When ...
>     Then ...

But this too scenarios I need to do every time. 

Maybe contain their and call from another scenario, like: 

> Scenario: 1
>     When ...
>     Then ...
> 
> Scenario: 2
>     When ...
>     Then ...
>
> Scenario: 3
>     Scenario 1
>     Scenario 2
>     When ...
>     Then ...

And when I do Scenario 3, I need do Scenario 1, 2 and when and then from scenario 3. 
I mean scenarios in scenario. But it can be problem with recursion.

**Comment by youtux** [comment]
I am not sure what you are trying to achieve with this style of test structure. Pytest-bdd does not support this; it's not a programming language.

**Comment by youtux** [comment]
Scenarios are like tests, you would not reuse the test body in another test.
@elchupanebrej in your example I do this instead:
```gherkin
Scenario: User logouts
  Given The user is logged in
  When User exits from account
  Then User sees a login page
```

and have a given step definition `@given("The user is logged in"): ...` that sets up the session cookie in the browser.
