### ISSUE TITLE
Gherkin V6 support

### ISSUE THREAD

**Issue by dunossauro** [pytest-dev/pytest-bdd#394]
Lately I've been using example mapping to write my scenarios.

Is there any support forecast for gherkin v6?

Gherkin reference: https://cucumber.io/docs/gherkin/reference/
Example mapping: https://cucumber.io/blog/bdd/example-mapping-introduction/

**Comment by youtux** [comment]
I will take that into account in https://github.com/pytest-dev/pytest-bdd/pull/395

**Comment by dunossauro** [comment]
@youtux, I would really like to help with the implementation.

I have no idea where to start. But, if it is possible to give me a direction, I would be VERY happy to contribute to this implementation.

A hug :heart:

**Comment by elchupanebrej** [comment]
Fork https://github.com/elchupanebrej/pytest-bdd-ng could be useful. It supports Gherkin>=19

**Comment by jsa34** [comment]
Now using the official parser; #728 and #738 address the outstanding features to be v6 compliant.
