### ISSUE TITLE
is there a hook for "before_feature" in pytest-bdd?

### ISSUE THREAD

**Issue by nik-wendt** [pytest-dev/pytest-bdd#396]
Looking at the hooks.py it appears not, but I'm also wondering if there is another way to achieve similar functionality? Specifically, I'd like to load test data specific to each feature file before test execution.

**Comment by youtux** [comment]
You can use an autouse fixture in your test module:

```python
# test_foo.py
from pytest_bdd import scenarios
import pytest

@pytest.fixture(autouse=True)
def my_data():
    ...

scenarios('foo.feature')
```

**Comment by nik-wendt** [comment]
This appears to run once per scenario instead of once per feature file. Just for added clarification i'm looking for functionality described by the before_feature function here: https://behave.readthedocs.io/en/latest/tutorial.html#environmental-controls

**Comment by youtux** [comment]
you can try to change the fixture scope to "module" and then just have one feature file per test module:

```python3
# test_foo.py
from pytest_bdd import scenarios
import pytest

@pytest.fixture(scope="module", autouse=True)
def my_data():
    ...

scenarios('foo.feature')
```

**Comment by felipeguedesalves** [comment]
I am also interested on this feature. Were you able to make it work @nik-wendt ?

On my scenario, I need multiple feature files on the same test module, so the [solution above](https://github.com/pytest-dev/pytest-bdd/issues/396?_pjax=%23js-repo-pjax-container#issuecomment-713383414) will not work.

**Comment by youtux** [comment]
@felipeguedesalves I'm afraid this use case is not supported.
