### ISSUE TITLE
Malformed feature results in test success

### ISSUE THREAD

**Issue by edinhodiluviano** [pytest-dev/pytest-bdd#399]
When a feature scenario has some mistake, the test runner returns it successfully tested that scenario.
A example would be:

```
# pytest_bdd_issue.feature
Feature: Issue

    Scenario: Scenario is malformed
        Then: fail
```
(there is a error in above file, a ":" after "Then")

```
# pytest_bdd_issue.py
from pytest_bdd import then, scenario

@scenario('pytest_bdd_issue.feature', 'Scenario is malformed')
def test_scenario_is_malformed():
    pass

@then('fail')
def fail():
    assert 0
```

But when running `pytest -vvv` it returns:
```
pytest_bdd_issue.py::test_scenario_is_malformed <- .venv/lib/python3.8/site-packages/pytest_bdd/scenario.py PASSED     [100%]
```

If --gherkin-terminal-reporter is enabled, it is possible to see that the scenario is incomplete. But it is unfeasible for large test suites to be eye checking all scenarios.

Would be possible to raise some error (SyntaxError maybe?!) when a scenario line cannot be parsed? At least a scenario line that starts with a keyword (Given, When, Then, And...)?

**Comment by youtux** [comment]
The parser will treat any line that doesn't match a step as a Description, that's why it succeeds. This is the design of the Gherkin language, we can't really fix that.

**Comment by edinhodiluviano** [comment]
Ok thanks.
Btw, super thanks for the prompt response : )

**Comment by youtux** [comment]
You are welcome :)
