### ISSUE TITLE
pytest-bdd Background is limited to one Then step, which has to be last

### ISSUE THREAD

**Issue by epkanol** [pytest-dev/pytest-bdd#408]
In https://github.com/pytest-dev/pytest-bdd/issues/118
support was added to allow pytest mixing When/Then steps in Scenarios.  (e.g. to create a flow of steps, with intermediate assertions)

However, the validation is still present in the Background section, and it is even forbidden to have multiple Then steps (or And).
Granted, it is not common to assert stuff in a background section, which mainly contains setup type of stuff. 
But in some cases assertions about external resources (host connections, data sources, files) could be made, and it is better to fail the test as soon as possible, in order to ease troubleshooting.

The obvious workaround is ugly - you could simply re-tag the needed assertion with a @when annotation - but this defeats the whole purpose of BDD, and violates the readability of Gherkin syntax. Also, in case external step libraries are used, it might not be practical.
Another, worse, workaround is to manally copy the needed background section into each and every test. This duplicates code, which always is a bad habit, especially for non-trivial systems.

Example showing the failure (comment the last line in the Background to make it work). The actual step implementation is not important, as this concerns the pytest-bdd parser:

Feature: Showing background issues
  
  Background: Only one Then step is supported by the pytest-bdd parser
    When  something happens in the background
    And   something happens in the background
    Then  something has happened in the background
    And   something has happened in the background

  Scenario: Test some list additions
    Given I have a list
    And   the list is empty
    When  I add an item to the list
    Then  the number of items in the list is 1
    When  I add an item to the list
    Then  the number of items in the list is 2

The relevant lines as I understood the issue (based on the exception stack trace) are: https://github.com/pytest-dev/pytest-bdd/blob/5d58fe3bbbf38d2408701f4876281a3440890522/pytest_bdd/parser.py#L124-L129

**Comment by olegpidsadnyi** [comment]
Gherkin supports only given steps in the background section. The priority now is to catch up with gherkin latest developments. https://cucumber.io/docs/gherkin/reference/#background
