### ISSUE TITLE
How can I define step defination inside a class by inheriting base setup

### ISSUE THREAD

**Issue by kunchamlokesh** [pytest-dev/pytest-bdd#421]
Hi,

I had requirement where I need to inherit the basesetup for tests by using a class with unittest framework

But in stepdefination when I tried create a class and call tests with @scenario tag by making scenarios as methods in the class an error got trigger as self is not a fixture 

Request to help me to declare @scenraios inside a class by inheriting another class

**Comment by youtux** [comment]
Sorry, this use case is not supported I'm afraid.
