### ISSUE TITLE
can we extend Gherkin language to support more convenient feature？

### ISSUE THREAD

**Issue by bulletRush** [pytest-dev/pytest-bdd#424]
* support step constant params so that we can reuse a step in one scenario or avoid some redundant examples
* support step param alias so that we can reuse a step in one scenario

I have implement this feature for my daily use. see: [support constant step params and step params alias](https://github.com/bulletRush/pytest-bdd/commit/4de85c23c239d55f7f1bf8954a516e95bd75e4db)

```feature
  Scenario Outline: variant step test
    When in situation: <case>
    Then return field: <field:k1> should has value: <value-v1>
    Then return field: <field:k2> should has value: <value-v2>
    Then return field: <field:k3> should has value: <value:hello world 你好，世界>
    Examples:
      | case | v1  | v2  |
      | 1    | v11 | v12 |
      | 2    | v21 | v22 |
```

**Comment by elchupanebrej** [comment]
Hi! Could you please provide more explicit examples of your usage?

For now, it's not very clear what semantic names like <field:k1> or <value-v1> have. Seems that field and value are new keywords?  Example feature definition doesn't provide context for variables k1, k2, k3. As it could be found in from source code this context is provided in step definition. IMO feature files have to be self-contained and must not be dependent on specific step realization / step context. BDD approach expects that feature files could be executed by hands or be readable by stakeholders. But in the case you have provided seems that there are some free variables, so such scenario could not be treated as ready for execution

**Comment by bulletRush** [comment]
k1, k2, k3 is constant value.

@elchupanebrej I fork pytest-bdd and add some feature for my daily use. see: [commits/master_ext
](https://github.com/bulletRush/pytest-bdd/commits/master_ext)

* constant example value and example value alias.  see example at [ext_test/ext.feature](https://github.com/bulletRush/pytest-bdd/blob/master_ext/tests/ext_test/ext.feature).
* support multi examples. see: [ext_test/multi_example.feature](https://github.com/bulletRush/pytest-bdd/blob/master_ext/tests/ext_test/multi_example.feature)
* [support auto load general steps](https://github.com/bulletRush/pytest-bdd/commit/4ccd949e6822ba60581aa8b2562d335b48175db6). add a new configuration: bdd_steps_def_dir

**Comment by bulletRush** [comment]
a more explicit example is we should check some fields of my data. so i have a line like `for reason <reason>, the field <field> should have value <value>`. if we support constant params, we will not need put our `reason` to examples, and we can reuse a sentence in one scenario.
