### ISSUE TITLE
Add support for flaky

### ISSUE THREAD

**Issue by danflucus** [pytest-dev/pytest-bdd#442]
hi,

It would be awesome if someone could add support for flaky: https://pypi.org/project/flaky/
I have 2,3 random failures that are impossible to fix and flaky would be great

Thx,
Dan

**Comment by The-Compiler** [comment]
Did you try whether it works? At least [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures/) does for me.

**Comment by jsa34** [comment]
It looks like a solution was found to use pytest-rerunfailures

Please open a new issue if you have issues.
