### ISSUE TITLE
Regression: KeyError in replacer

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-bdd#447]
With #445, I'm [seeing](https://github.com/qutebrowser/qutebrowser/runs/3695537911?check_suite_focus=true) many tracebacks like this in my tests:

```python
______________________ test_inserting_text_into_a_text_field_at_specific_position _______________________

request = <FixtureRequest for <Function test_inserting_text_into_a_text_field_at_specific_position>>
_pytest_bdd_example = {}

    @pytest.mark.usefixtures(*args)
    def scenario_wrapper(request, _pytest_bdd_example):
>       scenario = templated_scenario.render(_pytest_bdd_example)

.tox/bleeding/lib/python3.9/site-packages/pytest_bdd/scenario.py:173: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/bleeding/lib/python3.9/site-packages/pytest_bdd/parser.py:249: in render
    steps = [
.tox/bleeding/lib/python3.9/site-packages/pytest_bdd/parser.py:251: in <listcomp>
    name=templated_step.render(context),
.tox/bleeding/lib/python3.9/site-packages/pytest_bdd/parser.py:364: in render
    return STEP_PARAM_RE.sub(replacer, self.name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

m = <re.Match object; span=(18, 24), match='<Home>'>

    def replacer(m: typing.Match):
        varname = m.group(1)
>       return str(context[varname])
E       KeyError: 'Home'

.tox/bleeding/lib/python3.9/site-packages/pytest_bdd/parser.py:362: KeyError
```

There are many other such failures, but this one is from [this scenario](https://github.com/qutebrowser/qutebrowser/blob/v2.3.1/tests/end2end/features/yankpaste.feature#L289-L300):

```feature
    Scenario: Inserting text into a text field at specific position
        When I open data/paste_primary.html
        And I insert "one two three four" into the text field
        And I run :click-element id qute-textarea
        And I wait for "Entering mode KeyMode.insert (reason: clicking input)" in the log
        # Move to the beginning and two characters to the right
        And I press the keys "<Home>"
        And I press the key "<Right>"
        And I press the key "<Right>"
        And I run :insert-text Hello world
        # Compare
        Then the javascript message "textarea contents: onHello worlde two three four" should be logged
```

specifically, the `And I press the keys "<Home>"` line there.

The underlying [Python code](https://github.com/qutebrowser/qutebrowser/blob/v2.3.1/tests/end2end/features/conftest.py#L337-L340) is simple:

```python
@bdd.when(bdd.parsers.re('I press the keys? "(?P<keys>[^"]*)"'))
def press_keys(quteproc, keys):
    """Send the given fake keys to qutebrowser."""
    quteproc.press_keys(keys)
```

A [slightly simpler example](https://github.com/qutebrowser/qutebrowser/blob/v2.3.1/tests/end2end/features/caret.feature#L74-L80):

```feature
    Scenario: :selection-follow with link tabbing (without JS)
        When I set content.javascript.enabled to false
        And I run :mode-leave
        And I run :jseval document.activeElement.blur();
        And I run :fake-key <tab>
        And I run :selection-follow
        Then data/hello.txt should be loaded
```

with [this code](https://github.com/qutebrowser/qutebrowser/blob/v2.3.1/tests/end2end/features/conftest.py#L266-L291):

```python
@bdd.when(bdd.parsers.parse("I run {command}"))
def run_command(quteproc, server, tmpdir, command):
    # ...
```

results in a `KeyError: tab`. In other words, it seems like anything in `<...>` in a scenario now seems to be parsed in some special way.

---

I've tried to write a reproducer:

**bug.feature:**

```feature
Feature: Reproducer
    Scenario: Pressing keys
        When I run :fake-key <Ctrl+c>
        And I run :fake-key <tab>
```

**test_bug.py**:

```python
import pytest_bdd as bdd

bdd.scenarios('bug.feature')

@bdd.when(bdd.parsers.parse("I run {command}"))
def run_command(command):
    pass
```

but unfortunately, I can *not* reproduce the issue there. Any ideas what could be going wrong there?

**Comment by The-Compiler** [comment]
The changelog for 5.0.0 doesn't seem to indicate this anywhere - it links to a "Migration from 4.x.x" document which doesn't seem to exist.

Also, even if that's really the culprit, it seems to me like the error message should be a bit clearer than just an unhandled `KeyError` somewhere deep in pytest-bdd...

**Comment by dcendents** [comment]
as a workaround until this is fixed, if we use an examples table to feed the value it will work

Given the following step definition:

```python
@given(parsers.parse("variable {var} is set to '{value}'"))
def set_var(context, var, value):
    context[var] = value
```

This will fail:

```gherkin
Scenario: Test fail string with <value>
    Given variable v is set to 'some value with <value> in it'
```

This will pass:

```gherkin
Scenario: Test pass with example
    Given variable v is set to '<value>'

    Examples: Vertical
        | value | some value with <value> in it |
```

**Comment by bbatliner** [comment]
My apologies, the above comment has an issue already: #448. Including a solution that is tested.

**Comment by jirikuncar** [comment]
I am having a same issue but my step definitions contain text values with `<KEY>` that is not part of the example.

```cucumber
Feature: print values
  Scenario: print HTML tag
    Given tag p
    When printed with text
    Then the document contains "<p>text</p>"
```
raises `KeyError: 'p'`

**Comment by youtux** [comment]
Sorry for the inconvenience, when I implemented this change (to behave more according to the Gherkin specs) I didn't foresee this edge case. It seems that Gherkin does not mention how to workaround this issue in https://cucumber.io/docs/gherkin/reference/#scenario-outline.

I see a couple of options here to solve the problem:

1. One option is to apply templating only in scenarios that use the `Scenario Outline` (or `Scenario Template`) keyword, but it's still limiting what you can put in your steps in that case.

2. Another option is to proceed as suggested in https://github.com/pytest-dev/pytest-bdd/pull/465 and just silently ignore the fact that the render expected to render a parameter, and instead leave the original text. I'm not a big fan of this one though, as adding an `Example` table with `h1` would have unexpected consequences on the test (it would be testing something very different).

@olegpidsadnyi, what's your opinion on this?

**Comment by jirikuncar** [comment]
> adding an `Example` table with `h1` would have unexpected consequences on the test (it would be testing something very different).

I find it a less of a problem as it can be solved by renaming example parameters.

**Comment by elchupanebrej** [comment]
> 2\. Another option is to proceed as suggested in [Ignore </> in step parameter values #465](https://github.com/pytest-dev/pytest-bdd/pull/465) and just silently ignore the fact that the render expected to render a parameter, and instead leave the original text. I'm not a big fan of this one though, as adding an `Example` table with `h1` would have unexpected consequences on the test (it would be testing something very different).

3\. We could raise a warning. In case if it really wanted behavior user could just filter it out

**Comment by elchupanebrej** [comment]
Approach from #439 also could be a solution

**Comment by TBBle** [comment]
> Sorry for the inconvenience, when I implemented this change (to behave more according to the Gherkin specs) I didn't foresee this edge case. It seems that Gherkin does not mention how to workaround this issue in https://cucumber.io/docs/gherkin/reference/#scenario-outline.

For the record, the approach in Cucumber that hit the stage of "send a PR and we'll see" in https://github.com/cucumber/common/issues/1004 (before the issue timed-out a couple of years ago) was to use hot-comments to change the example-delimiter markers for a feature file.

AFAIK pytest-bdd doesn't support the existing `language` and `encoding` hot-comments in Gherkin, but the idea of using a different delimiter setting for a feature file (or at a different granularity, e.g. `@scenario`/`scenarios` which are the common user-facing API that already carry an `encoding` parameter) might allow resolving this issue for pytest-bdd users.

**Comment by youtux** [comment]
I'm fixing this in https://github.com/pytest-dev/pytest-bdd/pull/524 by parsing the params in angular brackets only for `Scenario Outline`s. Normal `Scenario` will treat them verbatim.

**Comment by elchupanebrej** [comment]
This fix could be ok for the current Gherkin dialect implemented in pytest_bdd, but in official gherkin language Scenario, Example and Scenario Outline are just aliases and all of them could be used with angular brackets

**Comment by elchupanebrej** [comment]
You are right! But internal implementation of the official Gherkin parser uses all of them as aliases.
