### ISSUE TITLE
Parametrized Scenario Outline not working

### ISSUE THREAD

**Issue by filipgon** [pytest-dev/pytest-bdd#452]
When attempting to run a feature file 
```
Feature: Parametrized Scenario Outline

    Scenario Outline: Parametrized Given, When, Then
        Given I have numbers {num1} and {num2}

        Examples:
        | num1 | num2 |
        | 2    | 4    |
```

with the following test step:

```
from pytest_bdd import given
from pytest_bdd.parsers import parse

@given(parse("I have numbers {num1} and {num2}"), converters=dict(num1=int, num2=int))
def parse_variables(num1, num2):
    assert isinstance(num1, int)
    assert isinstance(num2, int)
```

The parameters from the examples section are always read as strings, which in turn results in an assertion failure unless manually converted to the proper type, same when using `example_converters` within the scenario decorator.

Attempting to use format specification within the parser results in `StepDefinitionNotFoundError` being thrown.

**Comment by elchupanebrej** [comment]
Pretty strange, there is a test which tests exactly such behavior, you could find it at **tests.feature.test_outline.test_vertical_example**. Could you please double-check your environment?

**Comment by elchupanebrej** [comment]
> When attempting to run a feature file
> 
> ```
> Feature: Parametrized Scenario Outline
> 
>     Scenario Outline: Parametrized Given, When, Then
>         Given I have numbers {num1} and {num2}
> 
>         Examples:
>         | num1 | num2 |
>         | 2    | 4    |
> ```
> 
> with the following test step:
> 
> ```
> from pytest_bdd import given
> from pytest_bdd.parsers import parse
> 
> @given(parse("I have numbers {num1} and {num2}"), converters=dict(num1=int, num2=int))
> def parse_variables(num1, num2):
>     assert isinstance(num1, int)
>     assert isinstance(num2, int)
> ```
> 
> The parameters from the examples section are always read as strings, which in turn results in an assertion failure unless manually converted to the proper type, same when using `example_converters` within the scenario decorator.
> 
> Attempting to use format specification within the parser results in `StepDefinitionNotFoundError` being thrown.

"Given I have numbers {num1} and {num2}"  have to be replaced with "Given I have numbers <num1> and <num2>" at scenario definition.

**Comment by youtux** [comment]
This seems to be solved by @elchupanebrej [solution](https://github.com/pytest-dev/pytest-bdd/issues/452#issuecomment-1003630535). Closing this.
