### ISSUE TITLE
pytest-bdd 5.0.0_Example table values with spaces are not handled 

### ISSUE THREAD

**Issue by JagadeeshJayachandran** [pytest-dev/pytest-bdd#459]
Hi Team,

I have updated pytest-bdd to version 5.0.0, as suggested in the [https://pytest-bdd.readthedocs.io/en/stable/#migration-of-your-tests-from-versions-4-x-x]I have changed the way we call scenario outline table values from <> to {} using parser.

In our example table we have a field name **customer name** which has a value of **"Tony Max Jung"**, with the new approach of calling table values it only fetches **Tony**, basically ignores string after the space and assigns it to other parameters. Attached the screenshot.
`  Scenario Outline: fill forms
    Given I launch site abc
    When user enters <customer_name> <job>

    Examples:
      | customer_name     | job            |
      | Tony Max Jung     | Director of abc|
      | Tony Max Jung     | CEO of abc     |`
![pytest-bdd_issue](https://user-images.githubusercontent.com/51157326/139881174-567188bc-53ff-412c-a118-4e5b8c075366.PNG)

**Comment by elchupanebrej** [comment]
It happens because of how pytest-bdd works with parameters:
"When user enters <customer_name> <job>" is inlined with parameters and become:
"When user enters Tony Max Jung Director of abc" which is parsed with a step like:

@given(parse("When user enters {customer_name} {job}"))
def step_definition(customer_name, job)

In such case, parse doesn't know how exactly to fill two parameters. You could workaround this using width or precision templates as it's described here: https://pypi.org/project/parse/
or transform your step to include some separators like [], so your step will look like:
"When user enters [<customer_name>] [<job>]"
and step definition like:
@given(parse("When user enters [{customer_name}] [{job}]"))
def step_definition(customer_name, job)

**Comment by JagadeeshJayachandran** [comment]
Thanks for the response, I tried the above method you mentioned,  I am getting the error, any idea, please

Error: **parse() missing 1 required positional argument**


```
"When user enters [<customer_name>] [<job>]"
and step definition like:
@given(parse("When user enters [{customer_name}] [{job}]"))
def step_definition(customer_name, job)
```

**Comment by elchupanebrej** [comment]
Could you please provide which parse was imported? Seems you have used parse directly but not wrapper around it, who is provided by pytest_bdd:
`from pytest_bdd.parsers import parse`
And by example was inaccurate because of gherkin keyword:
```python
@when(parse("user enters [{customer_name}] [{job}]"))
def step_definition(customer_name, job)
```

**Comment by JagadeeshJayachandran** [comment]
Hi @elchupanebrej , I had to uninstall pytest-bdd-5.0.0 as it has a issue with allure reports and go back to Pytest-bdd-4.1.0. My question is I managed to use both example table values and parameters in single step using the method you suggested, I couldn't do the same with Pytest-bdd-4.1.0. Any advice, please.

**Feature file details:**
Then the user [<role>] validates the page including column names Case ID.

@then(parse("the user [{role}] validates the dashboard page including column names {Case ID}"))
def dashboard_page(role, Case ID):

**Comment by elchupanebrej** [comment]
```
@then("the user [<role>] validates the dashboard page including column names {Case ID}")
def dashboard_page(role, Case ID):
```

**Comment by elchupanebrej** [comment]
Combining of \<parameter> and {parsed_parameters} is not supported in pytest-bdd 4.x #293

**Comment by elchupanebrej** [comment]
Please provide info how allure was failed

**Comment by JagadeeshJayachandran** [comment]
@elchupanebrej Here is the issue raised [https://github.com/allure-framework/allure-python/pull/644](url).

Looks like the json file generated by allure along with pytest-bdd==5.0.0 is not compatible, we get error when we try to open the repost using the command `allure serve folder_path`

Error message: Could not read test result file targetreports/6557fe86-9aff-4b34-9198-2a61facbdff6-result.json

**Plugin versions:**
pytest-bdd==5.0.0
allure-pytest-bdd==2.9.45

allure report works fine with:
pytest-bdd==4.1.0
allure-pytest-bdd==2.9.45

**Comment by youtux** [comment]
Closing this as the issue seemed to be resolved. Feel free to comment if it's not the case.
