### ISSUE TITLE
Parse_type no longer builds with setuptools 58+

### ISSUE THREAD

**Issue by jonringer** [pytest-dev/pytest-bdd#494]
pytest-bdd is no longer supported for platform which consume packages as sdists (most package repositories). 

Related: https://github.com/jenisys/parse_type/issues/17

**Comment by elchupanebrej** [comment]
#495

**Comment by youtux** [comment]
Is this a problem of pytest-bdd? It seems it was a problem in parse_type, but that's now fixed, so I guess we can close this issue.

**Comment by elchupanebrej** [comment]
parse_type could be used separately from pytest_bdd and could be frozen with the elder version, so it's a defect. But I don't insist on this change

**Comment by jonringer** [comment]
this should be fine with the updated parse_type
