### ISSUE TITLE
Visual Studio Test Explorer

### ISSUE THREAD

**Issue by kappa10j** [pytest-dev/pytest-bdd#496]
How can we see the tests in the feature files in visual studio?

**Comment by youtux** [comment]
Hi, can you provide more info? I'm not sure what you expect.

**Comment by kappa10j** [comment]
I would like to see the feature file scenarios in test explorer

**Comment by youtux** [comment]
Sorry, I don't use visual studio code, I'm not really sure what is the test explorer in that context, PRs are welcome.
