### ISSUE TITLE
Pytest, @pytest.mark.skipif is not working.

### ISSUE THREAD

**Issue by MrNeo28** [pytest-dev/pytest-bdd#508]
@pytest.mark.skipif is not working, I've read and tried [this](https://github.com/pytest-dev/pytest/issues/8423) but it doesn't works for me. 

Features code
```
Feature: As a new user
    
   I am displayed with welcome screen

    Scenario: verify navigation of the application to login 
        Given User is on Language_selection  screen
        Then User select language
        Then User click on "DONE" button
```

Code:
```
lang = 'nl'  # some language
@pytest.mark.skipif(lang == 'nl', reason='Language Selection not available')
@given(parsers.parse('User is on {Language_selection}  screen'))
def validate(driver, Language_selection):
    # current screen validation
    RegisterationPage(diver).validate(Language_selection)
    print('it worked')
```

**Comment by youtux** [comment]
The `pytest.mark.skipif` is supposed to be applied to test functions. Here you are applying to the implementation of a step. 
What behaviour would you expect? To skip all the tests that use this step, or that the step is not executed, but the rest of the steps are?
I suggest you to instead write your own skip logic inside the step implementation.
