### ISSUE TITLE
Rule keyword

### ISSUE THREAD

**Issue by Poogles** [pytest-dev/pytest-bdd#511]
It'd be nice to have support for the [Rule](https://cucumber.io/docs/gherkin/reference/#rule) keyword and update for `Background`  to support rule level declarations.  Has anyone started on this?

For now global declarations of `Rule` at the top level are just treated as part of the feature description and passed through which is fine, but things break down when multiple rules are used to split a feature into it different scopes.

**Comment by rgilton** [comment]
Looks like this is already represented as a goal in #394

**Comment by elchupanebrej** [comment]
@youtux could you please review the approach in elchupanebrej/pytest-bdd#32

With official parser and model provided by that tool we could provide additional level of integrability for pytest-bdd

**Comment by elchupanebrej** [comment]
Fork https://github.com/elchupanebrej/pytest-bdd-ng could be useful. It supports Gherkin>=19

**Comment by Vic152** [comment]
+1
