### ISSUE TITLE
would you like reduce similar steps impl? 

### ISSUE THREAD

**Issue by bulletRush** [pytest-dev/pytest-bdd#512]
for this situation:

```feature
Given a phone
Given a <black> color phone
Given a <size>GB phone
Given a large dark phone
```

currently, we need write four step implements. in my ext version, we can write step impl like:

```python
@given("a phone")  # -> a white 1024GB phone
@given("a <color> color phone")  # -> a <color> 1024GB phone
@given("a <size>GB phone")  # -> a white <size> phone
@given("a large dark phone",  color="black", size=2048) # -> a black 2048GB phone
@given("a <color> color, <size>GB phone")  # -> a <color> <size> phone
def step_given_a_phone(color="white", size=1024):
    ...
```

if this feature is acceptable, i can make a PR to the latest version.

see commits:
- [support step args override](https://github.com/bulletRush/pytest-bdd/commit/9184593beabf70f4b882c9d9bc63a2423f21d575)
- [support step function default values](https://github.com/bulletRush/pytest-bdd/commit/b3c2987999a3149a7dbbde192dbbe0e21c7f8551)

**Comment by ktzoulas** [comment]
You can use fixtures for default parameters as a workaround. I have done this in the past for table parameters.

**Comment by bulletRush** [comment]
@ktzoulas You don't understand what I mean. for a better e.g.

```python
@then("the goods should sold out", available=True)
@then("the goods should not sold out", available=False)
def step_check_sold_out(ava, available=True):
        assert ava == available
```

in current pytest-bdd version, you need write two step defs: step_check_sold_out and step_check_not_sold_out.
but in my version, only need on step def.

**Comment by elchupanebrej** [comment]
@bulletRush could you please check https://github.com/elchupanebrej/pytest-bdd-ng and give your feedback if it covers your needs?

**Comment by youtux** [comment]
You can use a parser to achieve that result:

```python
from pytest_bdd import then, parsers

@then(
    parsers.re("the goods should (?P<negation>not )sold out"),
    converters={"negation": bool},
)
def step_check_sold_out(ava, negation):
    assert ava == not negation
```

**Comment by youtux** [comment]
You can also extend the `pytest_bdd.parsers.StepParser` base class, and add this logic in the `parse_arguments(...)` method. That's what this abstract base class is for.
