### ISSUE TITLE
Unable to Reuse Step with Scenario Outline Examples

### ISSUE THREAD

**Issue by MummanaSubramanya** [pytest-dev/pytest-bdd#514]
I have a situation where Im unable to reuse a step when using scenario outline. Below is an example 

**Example.feature**

Scenario Outline: 
Given I have Students list in database
When Student list is filtered with <last_name>
And Student list is filtered with <first_name>
And Student list is filtered with <student_age>
Then Student count is more than zero

Examples:
 | last_name| first_name| student_age|
 | xyz_ln       | xyz_fn.      | 20 |
 | xyz_ln       | fgh_fn.      | 21 |

**Stepdef.py** 

@when("Student list is filtered with <filter_value>")
def filter_student_list(context, filter_value):
      printf(f"logic for filtering the list with: {filter_value}" )

**Error:**

When I execute the the above example. It throws stepdef not found error. Reason is in stepdef.py I have used variable <filter_value> as a generic name. But pytest expects that in feature file we need to use the same variable name. Can you please help me in resolving this?

**Comment by elchupanebrej** [comment]
```python
from pytest_bdd.parsers import cfparse

from pytest_bdd.parsers import parse
from pytest_bdd.steps import when

@when(parse("Student list is filtered with {filter_value}"))
def filter_student_list(filter_value):
    print(f"logic for filtering the list with: {filter_value}")
```

**Comment by elchupanebrej** [comment]
We could reduce count of such questions after implementation of #472

**Comment by MummanaSubramanya** [comment]
I have udpated the code as you mentioned and it still fails with same error:

`Step definition not found: When "Student list is filtered with <last_name>"`

Stepdef.py

```
from pytest_bdd.parsers import parse
from pytest_bdd.steps import when

@when(parse("Student list is filtered with {filter_value}"))
def filter_student_list(filter_value):
    print(f"logic for filtering the list with: {filter_value}")

and Scenario.feature files is like this 
```

```
Scenario Outline: Sample Example
Given I have Students list in database
When Student list is filtered with <last_name>
And Student list is filtered with <first_name>
And Student list is filtered with <student_age>
Then Student count is more than zero

Examples:
| last_name| first_name| student_age|
| xyz_ln | xyz_fn. | 20 |
| xyz_ln | fgh_fn. | 21 |
```

**Comment by elchupanebrej** [comment]
Could you please provide info about:
- pytest_bdd version
- project layout

step definitions must be placed at conftest.py or in test modules.

**Comment by ktzoulas** [comment]
Try rename the step definition file to 'test_scenario.py' and import the 'scanerios' method to define the relative location of your feature file or just move the method in your 'congress.py'.

**Comment by MummanaSubramanya** [comment]
I have a very simple setup 

auto-tests
|
|----tests-----|---Myfeature.feature
|                        |---test_feature.py
|
|-----steps----|---conftest.py
                          |---given.py
                          |---when.py
                          |---then.py

**Comment by MummanaSubramanya** [comment]
Okay I was able to fix it but it just listerally prints the params which I set in feature file 

feature file: 
```
    Scenario Outline: Filter the student list
        Given I have student list
        And student list filtered with <first_name>
        And student list filtered with <last_name>
        Examples:
            | first_name    | last_name |
            | test_fn1      | test_ln1  |
            | test_fn2      | test_ln2  |

```

stepdefs:

```
@given(parsers.parse('I have student list'))
def student_list():
    print("Given student list")
    
@given(parsers.parse('student list filtered with {filter_value}'))
def filtering_the_student(filter_value):
    print("filtering with value: " + filter_value)
```

<img width="1430" alt="Screenshot 2022-04-27 at 11 25 44 PM" src="https://user-images.githubusercontent.com/25982124/165634013-f098c7d4-8a2e-4a79-83d3-6aae5920e919.png">

**Comment by ktzoulas** [comment]
Nice job! The parameters of each example are printed in the `Test` column, for example _tests/features/test_scenarios.py::test_scenarios[`test_fn1-test_ln1`]_. Not sure how you can override them, but you could try the https://github.com/wswebcreation/multiple-cucumber-html-reporter repo which accepts the JSON file generated using the `--cucumber-json` parameter and overrides their values.

**Comment by MummanaSubramanya** [comment]
I was expecting that pytest should convert that <first_name> to my example values which is test_fn1 and test_fn2 in stepdef too. 

Basically my expected result should look like this:

Given student list
filtering with value: test_fn1
filtering with value: test_ln1

**Comment by MummanaSubramanya** [comment]
Can we say its a bug on pytest side?

**Comment by elchupanebrej** [comment]
Could you please confirm that you use pytest>4

**Comment by MummanaSubramanya** [comment]
> Could you please confirm that you use pytest>4

please find the versions:

pytest==6.2.3
pytest-bdd==4.0.2

**Comment by elchupanebrej** [comment]
Combining of rendered steps and step parameters has been released in pytest_bdd==5.0 . The main discussion could be found in #293

**Comment by elchupanebrej** [comment]
I took the latest master and pytest==7.1.1:

![Снимок экрана 2022-04-28 165438](https://user-images.githubusercontent.com/2158101/165768612-7592ad99-ffb5-4419-99e6-f28804860f6a.png)

**Comment by MummanaSubramanya** [comment]
> I took the latest master and pytest==7.1.1:
> 
> ![Снимок экрана 2022-04-28 165438](https://user-images.githubusercontent.com/2158101/165768612-7592ad99-ffb5-4419-99e6-f28804860f6a.png)

Will check with latest version and revert back to you

**Comment by MummanaSubramanya** [comment]
I confirm that its working in my end.  Well let me test few more scenarios and will close if I dnt face any issues
