### ISSUE TITLE
New pytest bdd 6.0.1 doesnt take null values from the Examples within the scenario outline

### ISSUE THREAD

**Issue by Arundev404** [pytest-dev/pytest-bdd#551]
Steps to reproduce

1. Within a Pytest feature file try to have a scenario outline
2. Within example (just take example for a login page) as discussed
3.Scenario Outline: Login functionality with Negative password  and valid email
        Given User opens login in page
        When the User enters <invalid_password> into password and valid credential on the other textbox
        Then verify wrong_password will display a <warning_message> under the textbox
        Examples:
        |  invalid_password     |    warning_message                       |
        |                                    |    Password cannot be empty        |
        
        Step definition for the above scenario :
        def test_login_invalidPassword_Cases():
        pass

@when(parsers.parse('the User enters {invalid_password} into {textbox} and valid credential on the other textbox'))
def login_with_negative_password(textbox, invalid_password):
    Login_functions.fn_InvalidLogin(textbox, invalid_password)
        
  4. In the run time of the test ,the null value is getting as " " (double qoutes)

**Comment by youtux** [comment]
Hi, can you please reformat your post so that’s more readable? I’m on mobile at the moment, so it’s not easy for me to read it.

**Comment by Arundev404** [comment]
Hi @youtux 
did you got the chance to have a look into the issue

**Comment by youtux** [comment]
Please reformat your code so that it's readable.

**Comment by elchupanebrej** [comment]
@Arundev404 This is not a bug. If you need - you could use customer converter which converts empty string to None as described at https://github.com/pytest-dev/pytest-bdd#step-arguments

**Comment by jsa34** [comment]
I'll add a test for this as I've seen it mentioned a few times.  Here's an example I would use with a transformer to achieve what you requested:

```
Feature: Outline
    Scenario Outline: Outlined with empty example values and transformer
        Given there are <start> cucumbers
        When I eat <eat> cucumbers
        Then I should have <left> cucumbers

        Examples:
        | start | eat | left |
        | #     |     |      |
```

```
from pytest_bdd import given, when, then, parsers

def empty_to_none(value):
    return None if value.strip() == "" else value

@given(parsers.re("there are (?P<start>.*?) cucumbers"), converters={"start": empty_to_none})
def _(start):
    assert start == "#"            

@when(parsers.re("I eat (?P<eat>.*?) cucumbers"), converters={"eat": empty_to_none})
def _(eat):
    assert eat is None

@then(parsers.parse("I should have {left} cucumbers"), converters={"left": empty_to_none})
def _(left):
    assert left is None
```
