### ISSUE TITLE
Async when & then

### ISSUE THREAD

**Issue by j4k0bk** [pytest-dev/pytest-bdd#553]
I am implementing an end-to-end integration test suite using pytest-bdd. I need to execute multiple @when and @then asynchronously.

For instance, one @when might be moving a stepper motor, while another @when performs another real-time process (like playing a sound through a speaker). At the same, a @then is streaming feed from a camera and doing some image analysis on the motor's movement, while another @then is streaming from a microphone and doing frequency analysis.

Can this be accomplished using pytest-bdd? Thanks

**Comment by youtux** [comment]
Hi, pytest does not support this, and pytest-bdd makes use of the pytest infrastructure to run its tests.
Specifically, the fixture resolution part is completely delegated to pytest, so we can't really help with that until pytest adds support for async test execution.

**Comment by jruizaranguren** [comment]
@youtux There is https://github.com/pytest-dev/pytest-asyncio.
