### ISSUE TITLE
Unable to use pytest.marks with pytest-bdd step functions without test_ prefix

### ISSUE THREAD

**Issue by millerthegorilla** [pytest-dev/pytest-bdd#556]
Feature request...

Will it ever be possible to implement the ability to add pytest.marks to steps?

**Comment by youtux** [comment]
Can you provide a use case for it?

**Comment by jsa34** [comment]
Closing as use case is not clear.
@millerthegorilla please feel free to reopen with the requested details if this is still a request that you would like to raise.
