### ISSUE TITLE
Add py.typed file to distribution for mypy type checking

### ISSUE THREAD

**Issue by tiborsimon** [pytest-dev/pytest-bdd#559]
Running `mypy` against a project that uses `pytest-bdd` would result in errors like this:

```
error: Skipping analyzing "pytest_bdd": module is installed, but missing library stubs or py.typed marker  [import]
Untyped decorator makes function "..." untyped  [misc]
```

You have a nicely typed codebase (which is awesome!), but you need to make additional changes in your distribution setup to inform `mypy` to use those inline type annotations.

As a temporary local solution, adding a `py.typed` file to installed `pytest_bdd` package root (`.../site-packages/bytest_bdd/py.typed`) resolves the errors and `mypy` would pick up the inline type annotations.

Details from the `mypy` docs:
https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by youtux** [comment]
Thanks for the tip, I'll look into it!
