### ISSUE TITLE
Is there any way to execute test cases parallelly in pytest-bdd  (basic fundamental functionality request)

### ISSUE THREAD

**Issue by Enigmaderockz** [pytest-dev/pytest-bdd#584]
There should be some way to run pytest-bdd test cases parallelly using either annotation tags in feature file or multiple feature files something like this is currently lacking for sure. any help would be appreciated.

``
pytest-bdd -sv -m smoke test_test1.py
pytest-bdd -sv -m regression test_test1.py
``
or

``
pytest-bdd -sv test_test1.py
pytest-bdd -sv test_test2.py
``

**Comment by The-Compiler** [comment]
pytest-bdd tests are just pytest tests. There is pytest-xdist to parallelize them: https://pypi.org/project/pytest-xdist/

**Comment by Enigmaderockz** [comment]
thanks @The-Compiler . I tried with that using -n argument but it is not recognizing. 

could you please provide more details on the usage?

**Comment by nicoddemus** [comment]
@Enigmaderockz you seem to be running some `pytest-bdd` executable, but we understand that `pytest-bdd` should be run using the `pytest` executable.

What is `pytest-bdd` that you are using?

**Comment by Enigmaderockz** [comment]
yes... our organization has provided pytest-bdd file but not executable which has all the packages included
