### ISSUE TITLE
Step arguments are no longer fixtures

### ISSUE THREAD

**Issue by Ganjys** [pytest-dev/pytest-bdd#595]
Hello, 
I liked this feature, because I could access the parameter from the fixture.

So let's say I have a scenario outline
```
Scenario Outline: Test
    When Eat <amount> cucumbers
    Examples:
        |amount|
        | 2    |

```
When a step requests a fixture
```
@when(cfparse('Eat {amount} cucumbers'))
def step_function(amount,eat):
    do_something()
```
Fixture could easily access the step parameters
```
@pytest.fixture
def eat(amount):
    do_something()
```

I can't find anywhere in the documentation if there's another way to do this and I used this a lot in my tests, so without an alternative I can never upgrade pytest-bdd again.

**Comment by youtux** [comment]
You can probably achieve what you need this way:

```python
@when(cfparse('Eat {value} cucumbers'), target_fixture="amount")
def _(value):
    do_something()
    return value


@pytest.fixture
def eat(amount):
    do_something()
```

**Comment by Ganjys** [comment]
I didn't see any problems when executing my tests. As long as you remember to give parameters names that aren't the same as fixtures, it really wasn't a problem, but I can see how that becomes hard with multiple people working on the tests.

I ended Making each test a scenario outline with one row in the examples.
Then I can access them all with the 
step_parameters = request.node.funcargs['_pytest_bdd_example']
It required the least effort to fix the existing tests.

If it was parsed into fixtures then instead of removing it all together, it would have been nice to just add a dictionary request.node.funcargs that would contain them all, the same as pytest_bdd_example. That way the parameters could be easily shared to all the steps and fixtures throughout the tests if it was necessary while in the same time it wouldn't have interfered with people that don't use the feature.

**Comment by youtux** [comment]
be aware that `_pytest_bdd_example` is an internal fixture and that its behaviour or existence can change at any time without any note in the changelog, or without a major version bump.

**Comment by youtux** [comment]
The old way of injecting fixtures from example was very heavy to maintain and it didn't give us much flexibility. With the new approach, examples are substituted directly into the generated Scenarios, so that multiple scenarios can even interpret the example differently (using different parsers)

**Comment by youtux** [comment]
It is internal in the sense that we want to be able to change its implementation at anytime without having to support installations that rely on that technical detail.
