### ISSUE TITLE
parallel testing with pytest-bdd, x-dist, appium 2.0, allure-report is failed

### ISSUE THREAD

**Issue by DianPermana** [pytest-dev/pytest-bdd#601]
Hi All,

**I just want to run parallel testing in existing my code (**2 mobile android, with different OS**)**. let's say : 

A). devices = ANDROID10,  emulator-5554,  version = 10.0
B). devices = ANDROID12,  emulator-5555,  version = 12.0

**which part my statement is wrong**

1. I need 2 instance sever appium **ON** with different port (example, 4723, 4724)
2. I need to set @pytest.fixture(scope="function") def driver(request): programatically with different port
3. all requirment i set in addoption 

here all detail image configuration after I run my testing : 

A). Scenario outline 
![image](https://user-images.githubusercontent.com/18004033/220525225-c7270ead-3b86-4a96-8f24-084bb2a2d507.png)

B). Pytest Fixture and addoptions

  @@addoption
![image](https://user-images.githubusercontent.com/18004033/220525499-0bb9ca21-c5e9-46b0-839d-2e0d22020b96.png)

fixture
![image](https://user-images.githubusercontent.com/18004033/220525412-2ab78c6a-8f6d-4c38-9e2f-f6ccd803513f.png)

or via pytest.ini

![image](https://user-images.githubusercontent.com/18004033/220525888-f6109942-630d-428e-8196-1ee89be4211b.png)

C). run scenario 

![image](https://user-images.githubusercontent.com/18004033/220525711-c76213bb-6ded-412b-b7d9-f9542a638739.png)

D). Error
![image](https://user-images.githubusercontent.com/18004033/220525957-90ef4dfb-aa98-47e7-a35b-f7015225e66e.png)

Can anyone help me, thanks a lot in advance

**Comment by youtux** [comment]
Hi, this is not related to pytest_bdd. It seems you need to find a way to solve the error with Appium.
Closing this.
