### ISSUE TITLE
To get the current executing feature file name

### ISSUE THREAD

**Issue by CuriousQA** [pytest-dev/pytest-bdd#613]
how to get the current feature file which is under execution.

My project structure:
```
- features/
  - feature1.feature
  - feature2.feature
- tests/
  - test_check.py
```
test_check.py has 

```python
from pytest_bdd import scenario, scenarios, given, when, then, parsers

scenarios('../feature')
```

Able to get the function for the scenario
 request.node.nodeid gives scenario outline examples. However, is there a way to get the feature file name during the execution of test in any of the @Given or @when methods.

**Comment by mszpulak** [comment]
same here

**Comment by youtux** [comment]
you should be able to request the `request` fixture in your step definitions:

```python

@given("There is a foo")
def _(request):
    print(request.node.nodeid)
    return 42
```
