### ISSUE TITLE
Import from steps with a target_fixture collects the same test twice?

### ISSUE THREAD

**Issue by AmirYa412** [pytest-dev/pytest-bdd#630]
I am working on a refactoring a project from Behave to pytest-bdd.
Structure looks like this:

```
|---features
|          |---publish.feature
|---steps_def
|          |---conftest.py
|          |---test_article.py
|          |---test_publish.py     # scnearios() defined here


```
We have an internal Driver we initialise in `conftest.py`
In `test_article.py` I have steps that can be related to all features, "common steps".
I want to use defined steps freely in feature files, and use their `target_fixture` between other steps files.

I noticed few issues that stopping us from fully moving to pytest-bdd:

* Importing in `test_publish.py` steps or target_fixtures from `test_article.py` will collect the same scenario twice, in report I see the same scnario running from `test_aritcle.py` and `test_publish.py`.
* To use shared fixtures or steps I can define them in `conftest.py`, but is it really optimal? It will eventually create a really big `conftest.py` files, which I believe should contain configurations and not test related functions.
* If I don't import from `test_publish.py` and define the target_fixtures in `conftest.py`, I am getting: `pytest_bdd.exceptions.StepDefinitionNotFoundError` when running masks.feature.
* Only solution I can think of is creating a fixture in `conftest.py` - a fixture called `context` and pass it throughout the tests - but that's the reason we are moving from Behave - we don't want to use `context`.

**Comment by xiaorong22** [comment]
I encountered the same issue. I will keep an eye on it.

**Comment by xiaorong22** [comment]
I found you have already closed the issue. 
so could you tell me how to resolve this issue? thanks a lot!!
