### ISSUE TITLE
Feature discuss: pytest-bdd support StepMacros?

### ISSUE THREAD

**Issue by shihai1991** [pytest-dev/pytest-bdd#631]
Some other BDD framework support StepMacros，IMHO, it can help us manage the common steps.
In [Chorus BDD](https://www.chorus-bdd.org/pages/GherkinExtensions/StepMacro/), the example looks like:
```
#file: login.stepmacro
Step-Macro: I log in as user <user> with password <password>
    Given I click the login button
    And the login dialog is shown
    When I type <user> into the field username
    And I type <password> into the field password
    And I click the OK button
     
#file: login.feature
Feature: Log In 

    Scenario: I can log in using the login form
        Given I log in as user Nick with password myPassword
        Then I am logged in as the user Nick
    
#file: accountSummary.feature
Feature: Account Summary
 
    Scenario: Account summary link is shown when logged in
        Given I log in as user Nick with password myPassword
        Then the account summary link is visible on homepage
```

In [Behave](https://behave.readthedocs.io/en/latest/api/?highlight=macro#step-macro-calling-steps-from-other-steps), it looks like:
```
@when(u'I do the same thing as before with the {color:w} button')
def step_impl(context, color):
    context.execute_steps(u'''
        When I press the big {color} button
         And I duck
    '''.format(color=color))
```

**Comment by youtux** [comment]
You're welcome to open a PR for this.

The only restriction is that I don't think we should support "given" steps in the macro definition, as it doesn't make much sense to mix setup steps (givens) during the test execution.

**Comment by shihai1991** [comment]
> The only restriction is that I don't think we should support "given" steps in the macro definition, as it doesn't make much sense to mix setup steps (givens) during the test execution.

Aggree. Macro definition use in Then An When step would be more useful in my use case.
BTW, The Gherkin Plugin in PyCharm can't be extended to support this feature. Maybe we need suggest Cucumber Community accept this feature of Gherkin language firstly :)

**Comment by youtux** [comment]
Closing this unless it becomes supported by the language itself.
