### ISSUE TITLE
Internal pytest-bdd CONFIG_STACK error only occurring in Bamboo build

### ISSUE THREAD

**Issue by Zenthial** [pytest-dev/pytest-bdd#634]
I am getting this error, only in the Bamboo test build. The same tests execute fine on my local machine. It looks to be pytest not hooking the configuration impl in https://github.com/pytest-dev/pytest-bdd/blob/129cbc4fd2ec4087bfe312fa786240b4dd9e0975/src/pytest_bdd/plugin.py#L66

I would love some advice here.

![image](https://github.com/pytest-dev/pytest-bdd/assets/26680614/70d27689-8b61-4130-814a-8bd958e243c3)

**Comment by youtux** [comment]
I don’t know what bamboo is. Please provide an MVCE, otherwise I can’t make up your configuration.
