### ISSUE TITLE
Thanks for the great project!

### ISSUE THREAD

**Issue by jzohrab** [pytest-dev/pytest-bdd#640]
Hey all, I couldn't find a contact email etc, nor an open or closed issue, so here's a big thank-you for this super project.  I was considering writing something like this so imagine my relief to find this already implemented and available.  I converted my clunky yaml test defs to the feature format, wired up some steps, and done.

Thank you very much!

**Comment by youtux** [comment]
Hey thank you very much for your support, you don't hear appreciacion very often :)

**Comment by youtux** [comment]
cc @olegpidsadnyi
