### ISSUE TITLE
Refactor constants into an enum

### ISSUE THREAD

**Issue by JP-Ellis** [pytest-dev/pytest-bdd#647]
While fixing up some type hinting, I noticed that the `types.py` file,

https://github.com/pytest-dev/pytest-bdd/blob/57076695792ba9e865720f2d7aa5c6ae46f0befa/src/pytest_bdd/types.py#L1-L16

really functions more as an enum, and I think it should be refactored into one. I'm happy to help refactor this, though I would just want to understand whether one or multiple enums ought to be created.

The other benefit of using an Enum class is that certain functions specific to the handling of this enum could be refactor as class methods. For example:

https://github.com/pytest-dev/pytest-bdd/blob/57076695792ba9e865720f2d7aa5c6ae46f0befa/src/pytest_bdd/parser.py#L74-L84

**Comment by youtux** [comment]
yes absolutely, this was created way before enums appeared in python. Feel free to open a PR

**Comment by youtux** [comment]
I'll close this for now as it's not really an issue.
