### ISSUE TITLE
Issue with pytest-bdd Failing to Identify Correct Scenario Path After Folder Name Change

### ISSUE THREAD

**Issue by AliHezarpisheh** [pytest-dev/pytest-bdd#667]
After renaming folders in my project, I encountered an issue with pytest-bdd. It seems to struggle in locating the correct path, persistently searching for scenarios in the last path, which no longer exists.

Investigation:
Initially, I suspected caching problems. However, even after clearing the pytest cache, the error persisted. To further investigate, I played around with different folder names, and eventually, pytest successfully identified the existing folder.

Observation:
This behavior suggests that there might be an underlying issue in pytest-bdd related to handling folder name changes, extending beyond a simple caching problem.

Steps to Reproduce:

Rename folders in the project.
Run pytest to search for feature files.
Observe the search behavior.
Expected Behavior:
pytest-bdd should accurately identify the path even after folder name changes.

Additional Information:
If needed, I can provide more details or steps to reproduce the problem.

Appreciate your attention to this matter!

**Comment by youtux** [comment]
Please provide an MVCE to reproduce the issue.

**Comment by AliHezarpisheh** [comment]
1. Create a directory structure with nested folders containing feature files.
2. Rename one or more of these folders.
3. Run pytest-bdd to search for feature files within the project.
4. After renaming the folders, rerun pytest-bdd to observe its behavior.
5. Observe pytest-bdd's behavior in locating the feature files, specifically how it handles the renamed folders.

Additionally, I've found that deleting the __pycache__ folders resolves this issue. You may want to try this step as well.

**Comment by jsa34** [comment]
@AliHezarpisheh  

Is this still an issue with version 8.0.0?
Can I also ask how you are running pytest?

**Comment by AliHezarpisheh** [comment]
I have not encountered the issue for a while (and I don't know why).
I run pytest through the `pytest` command using this setting in `pyproject.toml`:

```toml
[tool.pytest.ini_options]
addopts = [
    "--strict-markers",
    "--strict-config",
    "-ra",
    "-v",
]
markers = [
    "smoke: Tests focusing on essential and critical functionality",
    "exception: Tests checking how the application handles exceptions and error scenarios",
    "asyncio: Asynchronous tests using the pytest-asyncio plugin",
]
required_plugins = [
    "pytest-randomly",
    "pytest-cov",
]

testpaths = "tests"
xfail_strict = true
```

**Comment by jsa34** [comment]
I'll take a look later and see if the commented setup results in the same behaviour.  If not, I will close and feel free to open if it happens again and if possible any more details about how it happened.

**Comment by AliHezarpisheh** [comment]
Great! I will be back with more details if the issue happens again.
