### ISSUE TITLE
How to apply for function/module/package/session scope to feature

### ISSUE THREAD

**Issue by gy95** [pytest-dev/pytest-bdd#687]
I know pytest-bdd can use pytest scope(function/module/package/session) by define a fixture by using scope="module", but this scope is belong to step file? i'm not really sure about this
But how to apply scope(like package) to a feature file

For example, i have a feature definition like below
```
Feature: feature one

  Background:
    # My requirement is that execute this step once when I run two scenarios: a and b.
    # how to apply this?
    Given step executed only once for both a and b

  Scenario: scenario a
    When sleep one second

  Scenario: scenario b
    When sleep one second
```
My requirement is that the `Given` step `step executed only once for both a and b` will only be executed only once when I run the two scenarios a and b. Can this requirement be met?

**Comment by gy95** [comment]
@youtux can this issue be fixed? Thanks a lot :)

**Comment by youtux** [comment]
Steps functions are not fixtures.

You can instead make a function decorator that prevents the function to execute a second time.
