### ISSUE TITLE
multiple test files are triggered by single feature file

### ISSUE THREAD

**Issue by chkp-lidorta** [pytest-dev/pytest-bdd#694]
hello,
I have a repository that includes :

```
Root dir 
    - Tests
          - test_1.py
          - test_2.py
    - features
          - 1_xray_ticket.feature
```
test_1.py is used for API testing, test_2.py is used for UI testing

they are built somewhat similar -

```python
from pytest_bdd import scenarios, given, when, then, parsers
import pytest

scenarios("path/to/features/folder")

# the rest of the logic (given when then)
```

When I trigger the pytest with the command - `python -m pytest -k / -m "tag from the feature file"`

It shows collection from both test files instead of only collecting the relevant sentences from the `.py` files

Am I missing something? Do I need to change one of my commands?

I tried multiple paths in Scenarios() option but nothing worked. Also tried using both `-m` and `-k` but again, nothing worked.

**Comment by AmirYa412** [comment]
I noticed it happens for me when I import a step or a function from `test_x.py` to `test_y.py`.
When I stopped doing such imports it no longer duplicate the tests.

Also in here: `scenarios("path/to/features/folder")` try to provide exact feature file and not a directory.

**Comment by chkp-lidorta** [comment]
I think my explanation was lacking.

The code is based on multiple Feature files being downloaded from Jira (XRAY plugin).

The tests folder includes multiple files - 
test_UI.py - UI related actions.
test_API.py - API related actions.
test_mail.py - Mails related actions.
and more....

some of the feature files could include steps from multiple files.
How do I configure the pytest bdd to support that?

**Comment by AmirYa412** [comment]
You have 2 options.

1. All steps you want to be shared between multiple features, you can write them in `conftest.py`.
Personally I don't like this approach. It can make `conftest.py`, and my aim is to keep this file to contain config related code only.

2. Divide you features to have their own directory, as well as 2 files in their directory:
```
feature
|--- test_feature.py 
|--- steps.py
```

test_feature.py - will contain only **assertions** (@then steps), related to the feature you are testing.
steps.py - contains steps related to this feature, that you can use in other feature's scenarios.

Now you can simply import in `conftest.py (you can also import them in any `test_feature2.py` file to make them available to the feature files connected in `scenarios()`` in that feature file)

`from feature.steps import *`

and those steps will be available in all of your feature files.
