### ISSUE TITLE
gherkin-official version bound raises `DeprecationWarning` on Python 3.13

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-bdd#752]
**Describe the bug**

When using a `@tag` with Python 3.13 and warnings enabled:

```console
$ pytest -Wall --no-header test_py313.py
============================= test session starts ==============================
collected 1 item                                                               

test_py313.py s                                                          [100%]

=============================== warnings summary ===============================
.tox/py313-pyqt67/lib/python3.13/site-packages/gherkin/gherkin_line.py:79
  /home/florian/proj/qutebrowser/git/.tox/py313-pyqt67/lib/python3.13/site-packages/gherkin/gherkin_line.py:79: DeprecationWarning: 'maxsplit' is passed as positional argument
    uncommented_line = re.split(r"\s#", self._trimmed_line_text.strip(), 2)[0]

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 1 skipped, 1 warning in 0.07s =========================
```

**To Reproduce**

`py313.feature`:

```gherkin
Feature: nothing
    @skip
    Scenario: nothing
```

`test_py313.py`:

```python
from pytest_bdd import scenarios
scenarios("py313.feature")
```

**Expected behavior**
No warning, as pytest-bdd should not have an upper gherkin-official bound, or at least have it on a more modern version.

**Additional context**
This was already fixed here: 

- https://github.com/cucumber/gherkin/pull/282
- https://github.com/cucumber/gherkin/pull/282/commits/2f4830093149eae7ff7bd82f683b3d3bb7320d39

And that was released as part of [v30.0.0](https://github.com/cucumber/gherkin/releases/tag/v30.0.0). However, pytest-bdd still pins an old version without full Python 3.13 compatibility:

https://github.com/pytest-dev/pytest-bdd/blob/9bb4967d9cbc907964b18bdbf84cd7a83ddb632d/pyproject.toml#L44

**Version**
 - pytest version: 8.3.4
 - pytest-bdd version: 8.1.0
 - OS: Archlinux

**Comment by youtux** [comment]
Fixing this in https://github.com/pytest-dev/pytest-bdd/pull/753, thank you for reporting it!

**Comment by The-Compiler** [comment]
Thanks for the quick fix! FWIW, here is an appropriate workaround for pytest's `filterwarnings`:

```
ignore:'maxsplit' is passed as positional argument:DeprecationWarning:gherkin.gherkin_line
```
