### ISSUE TITLE
# is unconditionally treated as a comment starter

### ISSUE THREAD

**Issue by santagada** [pytest-dev/pytest-bdd#99]
There should be a way to escape a # or even better, if it is inside quotes or on a table it should be treated as data.

**Comment by bubenkoff** [comment]
where exactly you experience issues?
can you please give an example?

**Comment by santagada** [comment]
I have a scenario in portuguese:

Scenario: Carregar a agenda da editoria Ar Livre
    When eu navego para o site
    And eu clico no "Agenda"
    And eu clico no "Ar Livre"
    Then eu deveria estar em "/agenda/ar-livre"
    And eu deveria ver um bloco "#destaques-da-agenda"

the last step is defined as:

@then(parsers.parse('eu deveria ver um bloco "{bloco}"'))
def eu_deveria_ver_um_bloco(bloco, browser):
    assert browser.find_by_css(bloco).first

but the parser finds the first # and don't see the rest of the string, giving the error:
StepDefinitionNotFoundError: Step definition is not found: "eu deveria ver um bloco "\".

I have an idea to search for a regex and not the first #. Like using '(^|(?<= ))#' instead of of only looking for the first index of '#'.

To make it even more restrictive I would search for two spaces before a pound, this would put it inline with python pep8 recomendation, but maybe break text editors syntax highlighting and is not backward compatible.

**Comment by bubenkoff** [comment]
thanks for the detailed report!
i'll take a look as soon as possible

On 15/03/2015, Leonardo Santagada <notifications@github.com> wrote:
> I have a scenario in portuguese:
>
> Scenario: Carregar a agenda da editoria Ar Livre
>     When eu navego para o site
>     And eu clico no "Agenda"
>     And eu clico no "Ar Livre"
>     Then eu deveria estar em "/agenda/ar-livre"
>     And eu deveria ver um bloco "#destaques-da-agenda"
>
> the last step is defined as:
>
> @then(parsers.parse('eu deveria ver um bloco "{bloco}"'))
> def eu_deveria_ver_um_bloco(bloco, browser):
>     assert browser.find_by_css(bloco).first
>
> but the parser finds the first # and don't see the rest of the string,
> giving the error:
> StepDefinitionNotFoundError: Step definition is not found: "eu deveria ver
> um bloco "\".
>
> I have an idea to search for a regex and not the first #. Like using
> '(^|(?<= ))#' instead of of only looking for the first index of '#'.
>
> To make it even more restrictive I would search for two spaces before a
> pound, this would put it inline with python pep8 recomendation, but maybe
> break text editors syntax highlighting and is not backward compatible.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pytest-dev/pytest-bdd/issues/99#issuecomment-81011117


-- 
Anatoly Bubenkov

**Comment by santagada** [comment]
I've sent a pull request, now with tests for it.

**Comment by bubenkoff** [comment]
@santagada can you please tell a bit about your experience with pytest-bdd?
knowing more about your usecase/needs will help to make project better so it's win-win situation

**Comment by santagada** [comment]
I'm looking at a tool for browser testing a big wordpress site, so it is mostly selenium functional tests.

**Comment by bubenkoff** [comment]
Then it should fit ideally. Slight overhead of creating a library of step
definitions will be paid by maintainability and code readability and
minimalism.
You certainly want to use pytest-splinter as well
